### ISSUE TITLE
Seems like the router does not check for 'in queue' testing sessions

### ISSUE THREAD

**Issue by MiluchOK** [aerokube/ggr#102]
I am getting some kind of a 'wave' effect when a lot of sessions would be redirected to the same node and the router will keep sending sessions there until my grid will assign most of the queued sessions to nodes. I am using Zalenium, so when no sessions requested my hub technically has 1 node, but they are being created and attached to hub automatically. 

In the nutshell what I am requesting is not to only check for active nodes attached to hub, but also for queued sessions and if there is a lot in the queue , redirect traffic to different hub. 

I am really satisfied with the ggr tool, it is awesome, but this problem is overloading my hubs and I cannot scale.

**Comment by vania-pooh** [comment]
@MiluchOK this is impossible because of stateless Ggr architecture. It does not store any information about total number of occupied browsers for each host and does not limit session requests. We consider this as hub responsibility. For example Selenoid has queue functionality which allows to limit maximum number of Docker containers to be started. Selenium hub normally also has this functionality, not sure about Zalenium.

**Comment by MiluchOK** [comment]
Wait , but what is the 'count' param in the quota file then?

**Comment by vania-pooh** [comment]
It is the `host weight` for random distribution, not the total number of browsers. This name is rather confusing but we leave it for backwards compatibility.

**Comment by MiluchOK** [comment]
Got it! Thanks! Closing the issue than.

**Comment by DeChrish** [comment]
@vania-pooh  i have a clarification regarding the above question:

we are launching using selenoid as hub in ggr architecture.
1. Is it possible to increase new session timeout while launching selenoid?
2. Can we limit the node count from the selenoid? Ex use only 20 session at a time

**Comment by vania-pooh** [comment]
@DeChrish session timeout can be increased either globally with `-timeout` flag or using `sessionTimeout` capability on per-session basis. https://aerokube.com/selenoid/latest/#_custom_session_timeout_sessiontimeout
