### ISSUE TITLE
ggr cannot discover selenoid 

### ISSUE THREAD

**Issue by MiluchOK** [aerokube/ggr#103]
I don't know why but ggr thinks that my selenoid hub is down. 
I confirmed that the selenoid is up and running and I can curl it's status from ggr container. 

In my setup I have ggr running on k8 and selenoid on a dedicated aws machine. 
In the ggr logs I can see it's trying to put load on the selenoid machine, but says that it is down.

**Comment by MiluchOK** [comment]
2017/07/20 22:13:12 [2181] [SESSION_ATTEMPTED] [test] [172.21.0.31, 172.21.0.45] [chrome-59.0.3071.115] [172.31.11.134:4444] [1]
2017/07/20 22:13:12 [2181] [SESSION_FAILED] [test] [172.21.0.31, 172.21.0.45] [chrome-59.0.3071.115] [172.31.11.134:4444] Requested environment is not available

**Comment by MiluchOK** [comment]
Also when I hit the selenoid directly, skipping the ggr. Everything works just fine.

**Comment by MiluchOK** [comment]
nvm, found the issue, selenoid says that it does not know such browser version if I run through ggr. But it is still unknown for me why the same test with the same browser request worked when I was using selenoid without ggr. 🤔

**Comment by vania-pooh** [comment]
@MiluchOK please show me your `browsers.json` and `test.xml`.

**Comment by vania-pooh** [comment]
@MiluchOK any updates?

**Comment by vania-pooh** [comment]
@MiluchOK ping.

**Comment by MiluchOK** [comment]
Uh, sorry, I thought I closed it, yes, the browsers.json and test.xml had different versions. 
Both ggr and selenoid works great! And I've added prometheous and grafana on top, so now I have some statistics. Hopefully nothing breaks :crossed_fingers:  And I'm waiting on options to record videos! Great job guys!
