### ISSUE TITLE
Hub selection logic algorithm not correct?

### ISSUE THREAD

**Issue by langrasm** [aerokube/ggr#113]
Hi 

First off all thanks for the create job!. We can now successful use selenium testcases for loadtesting. I don't know if this is the correct way to submit an issue/question. If not please let me know.

The issue: 
We have configured 10 hubs in the quota xml file. These 10 hubs can build max 5 nodes. They are configured for the same region using the same chrome browser version. In the quota file we did configure the count="5" for all hubs. 

When we start 40 parallel testcases against the Go Gridrouter we would expect the router to divide/allocate the 40 testcases over the hubs available in the quota xml file.  We have set the count="5" for all 10 hubs. So we would expect if there are enough hubs there could not be more then 5 parallel session per hub. 

What we now see is that the  Go Gridrouter divide/allocate more then 5 testcases per hub. Some hubs are getting 10, others are getting 3 etc. In this way we cant guarantee for example 40 concurrent / parallel testcases.

We have checked the hub selection logic:
2.	Randomly selects a host from all hosts and tries to obtain browser on that host. Our algorithm also considers browser counts specified in XML for each host so that hosts with more browsers get more connections.

Is this a bug or as designed? Can we make this work?

Thanks in advanced
Best Regards
Michel Langras

**Comment by vania-pooh** [comment]
In general because of random distribution this situation is possible. More hosts you have - more smooth is the distribution. Now we have 3 working Ggr usage patterns:

1) Ggr + Selenoid + queues enabled: works well with any load even greater than total number of available browsers.

2) Ggr with `-timeout` flag + Selenoid + queues enabled: in that case Ggr wait specified time before going to next host. This makes distribution more smooth.

3) Ggr + Selenoid + queues disabled: this works well only if you know your maximum load.

**Comment by langrasm** [comment]
Hi Vania-pooh

Thanks for the response. We will try the Ggr + Selenoid + queues enabled. We now using Ggr + zalenium. You are referring to queues enabled? Does this only work with Selenoid?

What we want to achieve is a loadtest with constantly 95 parallel sessions. So, we have 19 zalenium hubs configured in the quota xml file. We have set the count="5" for each host. This is because the hub is most stable with max 5 nodes.  We have configured the Zalenium hub to only have 5 nodes.

Is it possible for Go Gridrouter to not assigning more then 5 parallel tests to a hub. If all 5 nodes are busy, gridrouter needs to try another hub. Until a free node is found.  This will mean there are always 95 parallel sessions until the loadtool is finished.

**Comment by vania-pooh** [comment]
@langrasm 
1) Just for your information - if you are using Zalenium to proxy to commercial services like Saucelabs, then Ggr can also do this - i.e. send username and password to the "Saucelabs hub".
2) Zalenium being an extension of Selenium server has queues always enabled. You can only achieve desired result by using Selenoid and disabling queues via `-disable-queue` flag.

**Comment by langrasm** [comment]
@Ivan<mailto:notifications@github.com> The main reason for using Zalenium is that they never reuse nodes. When you ask the hub for 5 nodes they will be created and used for running the testcases. When the testcase is done the node will be closed again. From our test we did see when nodes are reused they get instable. So without Zalenium we restarted all the hubs after every testrun.

We will give Selenoid with disabling queues flag a try and see if we can manage to get up to a 100 parallel sessions. We will update this post.


Outlook voor Android<https://aka.ms/ghei36> downloaden



Van: Ivan Krutov
Verstuurd: vrijdag 1 september 17:05
Onderwerp: Re: [aerokube/ggr] Hub selection logic algorithm not correct? (#113)
Aan: aerokube/ggr
Cc: Michel Langras, Mention


@langrasm<https://github.com/langrasm>
Just for your information - if you are using Zalenium to proxy to commercial services like Saucelabs, then Ggr can also do this - i.e. send username and password to the "Saucelabs hub". Zalenium being an extension of Selenium server has queues always enabled. You can only achieve desired result by using Selenoid and disabling queues via -disable-queue flag.

**Comment by vania-pooh** [comment]
@langrasm Selenoid is starting a new container for every browser session. So this is the same behavior.

**Comment by vania-pooh** [comment]
@langrasm any more things to do here?

**Comment by langrasm** [comment]
Hi Ivan

We have switched to Selenoid (with the -disable-queue flag) for all our hubs and it work really well!. The Go Gridrouter does not assign to many testcases anymore to a Selenoid hub that does only have 5 nodes. However, we are still not there yet. We can build up 95 nodes using 19 Selenoid hubs. We are running 3000 selenium testcases with an average duration of 20 seconds. So, in theory we could handle 95 testcases per 20 seconds. We should manage todo around 285 testcases in 1 minute. With this speed the test would finish in around 10minutes.

In practice, the max is around 61 testcases per minute. If we look in the ggr logging the queued are 0. But there is too much “pending”. We would expect to see the “used” is constantly on 5 for all hubs as long as the TestSuite with 3000 testcases is running. However, that is not the case. Some hubs do have 0 “used” for to long.

We are now looking at the code to see if we can adjust the code to speed up grr, so there will never be hubs with 0 “used”.

Regards
Michel

Van: Ivan Krutov [mailto:notifications@github.com]
Verzonden: vrijdag 8 september 2017 16:11
Aan: aerokube/ggr <ggr@noreply.github.com>
CC: Michel Langras <Michel.Langras@mansystems.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [aerokube/ggr] Hub selection logic algorithm not correct? (#113)


@langrasm<https://github.com/langrasm> any more things to do here?

**Comment by aandryashin** [comment]
Hello Michel

I would recommend that you try to enable queue on selenoids and run all
your 3000 testcases simultaneously. In that case grid router distribute all
requests across 95 nodes, selenoids will keep pending tests in queue and
process them immediately when running tests completed. Please try this
scheme and compare with your results.

2017-09-08 17:35 GMT+03:00 langrasm <notifications@github.com>:

**Comment by vania-pooh** [comment]
Just released version [1.2.7](https://github.com/aerokube/ggr/releases/tag/1.2.7) with hub selection logic fix. Please check whether it works better for you considering what was stated above.

**Comment by langrasm** [comment]
Hi 

Hereby some of the test results. We have tested with the enable and disable queue. And the new ggr 1.2.7 version.  In the testresults we can see when disabling the queue, the ggr works better/faster.  When the queue is enabled some of the hubs get to many test-cases assigned. That will result in some of the hubs have a bigger queue than the others. So, in the end of the loadtest 3 out of 20 hubs are still processing. This will slowdown the per minute processing of testcases. It should work better if ggr notice a free hub and reassign testcases. So from begin until the end of the loadtest all 20x5 nodes do have testcase assigned and are processing. 

However, the goal was 180 correct testcases per minute. And we have reached this goal!
Loadtest datadriven with 1000 users. (set to 80 parallel, queue disabled) Loadtest in 4min. 874 testcases are completed.
Total: 250 per minute 
Completed: 218 per minute

We still need to investigate why so many testcases are failing, And if this have something todo with the load on the infrastructure or maybe on the app that we are loadtesting.

If you can make some more optimizations to ggr, so it will always use all available nodes during the loadtest that would be great. For now already thanks for the great support!

**Comment by vania-pooh** [comment]
@langrasm in Ggr 1.5.2 we improved load balancing logic when working with Selenoid. The main idea is that Selenoid returns an error to Ggr when full when a particular HTTP header is set and Ggr automatically skips such hosts until it reaches the last available host. Ggr then waits in last host queue. This gives effectively uniform distribution because hosts are being chosen randomly. I consider this fixed.

**Comment by yuandanxu** [comment]
@vania-pooh , I encountered similar issue and wants to seek some help. I'm using ggr + zalenium to run our UI test cases. I set up 6 zalenium hubs, each hub has 4 containers. When using ggr, the test cases are executed very slow and seems hang. I want to confirm two questions:
1. do ggr support zalenium? Is there any configuration I need to do?
 docker run -d -ti --name zalenium -p 4445:4444    -e NODE_MAX_INSTANCES=5  -v /var/run/docker.sock:/var/run/docker.sock       -v /tmp/videos:/home/seluser/videos       --privileged dosel/zalenium start --chromeContainers 6 --maxTestSessions 150
docker run -d --name ggr -v /etc/grid-router/:/etc/grid-router:ro --net host aerokube/ggr:latest-release
2. If I want to change from zalenium to selenium, what do I need to do? Just change driver.quit to close?

Thanks a lot.

**Comment by vania-pooh** [comment]
@yuandanxu 
1) We support any Selenium API behind Ggr: Selenium server, Zalenium or our own fast implementation called [Selenoid](https://github.com/aerokube/selenoid).
2) You should always use `driver.quit()` to close the session! Otherwise you are closing window tabs and the session. This usually leads to not closed browsers (they are closed only after timeout expires) and all browsers are exhausted.

**Comment by vania-pooh** [comment]
@langrasm see https://aerokube.com/ggr/latest/#_working_with_external_selenium_services. I think SauceLabs should queue itself,

**Comment by DeChrish** [comment]
@vania-pooh SL queue has a limit in time I(10 mts) we want to use grid queue.

**Comment by DeChrish** [comment]
@vania-pooh ggr will not use selenoid queue?

**Comment by vania-pooh** [comment]
@DeChrish it will.
