### ISSUE TITLE
Ability to proxy VNC port

### ISSUE THREAD

**Issue by vania-pooh** [aerokube/ggr#117]
Similarly to Selenoid:
```
/vnc/<session-id> - should proxy tcp traffic to host port 5900 over web-sockets
```

**Comment by benzman81** [comment]
Nice one, but port should be configurable, as it is not always 5900 ;-)

**Comment by aandryashin** [comment]
Ggr will proxy to selenoid /vnc/<sessionID> and selenoid will proxy to
appropriate port.

20 сент. 2017 г. 12:56 ПП пользователь "Markus Krüger" <
notifications@github.com> написал:

**Comment by vania-pooh** [comment]
@aandryashin for some cases, e.g. real devices behind Ggr we need to think how to proxy directly.
@benzman81 sure, this should be customizable.

**Comment by benzman81** [comment]
Would be great, if the port would also be available in the json of the /host/* end point.

**Comment by vania-pooh** [comment]
@benzman81 seems to be a good idea.
