### ISSUE TITLE
Unevenly load balancing 

### ISSUE THREAD

**Issue by FiremindHub** [aerokube/ggr#119]
Hi! I have two Selenoid hubs with diffenent performanfe and ggr with config: 
```
<host name="10.0.14.XX" port="4444" count="1"/>
<host name="10.0.12.XXX" port="4444" count="1"/>
```
And I see, that hub with 5 nodes have more load, then hub with 10 nodes. Are hubs must have the same number of nodes?

here the screenshot of both hubs ui: https://imgur.com/a/qzCte

**Comment by aandryashin** [comment]
Please adjust count attribute for appropriate values, use count=5 for
selenoid with 5 nodes and count=10 for selenoid with 10 nodes...

28 сент. 2017 г. 8:08 ДП пользователь "Firemind" <notifications@github.com>
написал:

**Comment by FiremindHub** [comment]
Seems, it helped. Thank you!
