### ISSUE TITLE
What does count attribute do in quota file?

### ISSUE THREAD

**Issue by ryan-levell-twc** [aerokube/ggr#132]
I started Selenoid with docker: `aerokube/cm:latest selenoid start --port 4445 --args "-limit 20"`

I then created a quota file with:

`user.xml`
```
<qa:browsers xmlns:qa="urn:config.gridrouter.qatools.ru">
<browser name="chrome" defaultVersion="62.0">
    <version number="62.0">
        <region name="1">
            <host name="1.2.3.4" port="4445" count="10"/>
        </region>
    </version>
</browser>
</qa:browsers>
```

When I run with this user it runs 20 in parallel. I thought `count="10"` would mean this user can do at most 10 in parallel. And `-limit 20` was the max for the VM. Is this a potential bug, or is that `count` for something else?

**Comment by vania-pooh** [comment]
No, `count` is in fact a host weight of the host and makes sense when two or more hosts are present in quota. This attribute is called so for historical reasons. So when you have e.g. two hosts in quota with counts `1` and `3` then sessions will be distributed as `1:3` over these hosts. It should be clear that when counts are equal then distribution should be uniform. If you set `count` equal to the real count of browsers for each host - then you also get uniform distribution. This is what we are usually doing in production.

**Comment by vania-pooh** [comment]
Btw, we are currently developing our Q&A set on StackOverflow. Could you duplicate this question there?

**Comment by ryan-levell-twc** [comment]
https://stackoverflow.com/questions/47205931

**Comment by vania-pooh** [comment]
Answered in question.
