### ISSUE TITLE
Is there a wildcard or IP-range option for the browser host?

### ISSUE THREAD

**Issue by ryan-levell-twc** [aerokube/ggr#133]
I was looking into AWS autoscaling groups. One initial problem is that any new hubs will not be in the browser XML.

Is there some kind of wildcard option? `<host name="*.example.com" port="4444" count="1"/>`

or some kind of IP range or CIDR block? `<host name="1.2.3.4/24" port="4444" count="1"/>`

Or is there some way to make auto scaling work?

**Comment by vania-pooh** [comment]
Currently this is completely static and we only support static hostnames. How would Ggr determine which hosts to use having e.g. `*.example.com`? Should we fetch all DNS records somewhere? We could implement something like this - let's discuss and find a simple solution.

One possible solution if your hosts are following some pattern, e.g. `my-host-[1:10].example.com` is to use [sctl](http://github.com/seleniumkit/sctl) to generate XML quota files.

**Comment by ryan-levell-twc** [comment]
Yes I threw those out there as a conversation starter. Currently I just use IP addresses in AWS. A VPC is created with an IP range. Would it be too slow to check all possible IPs in that range with Ggr? I guess it depends on how large the range is. I think common CIDR numbers for selenium would be `/32`-`/24` e.g. 1-254 IP addresses.

For domains, `sctl` looks interesting. I think that is a good approach for domain names. Would you notify all Ggr's that a new hub is available and to rerun `sctl`?

**Comment by vania-pooh** [comment]
Our production configuration is still static. We are using `sctl` to avoid copy-paste issues in multiple XML files. `sctl` is working with text - it does not know whether it is processing host names or IP addresses. So you could just use the following notation in its JSON file: `1.2.3.[1:254]`. This will generate `<host/>` entries with IP addresses. You can generate such XML files once and then test whether it is fast or not. I think if the total number of IPs remains small - then trying all of them should be relatively fast - just open Selenium port and Ggr will quickly receive `connection refused` errors for missing hosts and try to choose another one.

**Comment by ryan-levell-twc** [comment]
That makes sense. This is easy and requires no new features :) Thank you.

**Comment by vania-pooh** [comment]
@ryan-levell-twc when you try please give some feedback whether such approach is efficient.

**Comment by ryanlevell** [comment]
@vania-pooh I tried with a `/26` subnet, 64 IP addresses. I currently have a single hub running.
It took 34 tries to find the correct hub IP. Each try has a 30 second timeout so this took 17 minutes to find the hub, shown below.

I started Ggr with `-timeout 4s`, but this is still too slow when looking through 64 IPs. I tried to change to `250ms` but then the wait is too short and even the correct hub times out.

```
2017/11/14 18:02:27 [1] [SESSION_ATTEMPTED] [my-user] [my-ip] [firefox-56.0] [172.1.0.16:4445] [1]
2017/11/14 18:02:57 [1] [SESSION_FAILED] [my-user] [my-ip] [firefox-56.0] [172.1.0.16:4445] 
2017/11/14 18:02:57 [1] [SESSION_ATTEMPTED] [my-user] [my-ip] [firefox-56.0] [172.1.0.4:4445] [2]
2017/11/14 18:03:27 [1] [SESSION_FAILED] [my-user] [my-ip] [firefox-56.0] [172.1.0.4:4445] 
2017/11/14 18:03:27 [1] [SESSION_ATTEMPTED] [my-user] [my-ip] [firefox-56.0] [172.1.0.62:4445] [3]
2017/11/14 18:03:57 [1] [SESSION_FAILED] [my-user] [my-ip] [firefox-56.0] [172.1.0.62:4445] 

[... truncated tries 4-29 ...]

2017/11/14 18:16:57 [1] [SESSION_ATTEMPTED] [my-user] [my-ip] [firefox-56.0] [172.1.0.38:4445] [30]
2017/11/14 18:17:27 [1] [SESSION_FAILED] [my-user] [my-ip] [firefox-56.0] [172.1.0.38:4445] 
2017/11/14 18:17:27 [1] [SESSION_ATTEMPTED] [my-user] [my-ip] [firefox-56.0] [172.1.0.43:4445] [31]
2017/11/14 18:17:57 [1] [SESSION_FAILED] [my-user] [my-ip] [firefox-56.0] [172.1.0.43:4445] 
2017/11/14 18:17:57 [1] [SESSION_ATTEMPTED] [my-user] [my-ip] [firefox-56.0] [172.1.0.15:4445] [32]
2017/11/14 18:18:27 [1] [SESSION_FAILED] [my-user] [my-ip] [firefox-56.0] [172.1.0.15:4445] 
2017/11/14 18:18:27 [1] [SESSION_ATTEMPTED] [my-user] [my-ip] [firefox-56.0] [172.1.0.22:4445] [33]
2017/11/14 18:18:57 [1] [SESSION_FAILED] [my-user] [my-ip] [firefox-56.0] [172.1.0.22:4445] 
2017/11/14 18:18:57 [1] [SESSION_ATTEMPTED] [my-user] [my-ip] [firefox-56.0] [172.1.0.25:4445] [34]
2017/11/14 18:18:58 [1] [991.80s] [SESSION_CREATED] [my-user] [my-ip] [firefox-56.0] [172.1.0.25:4445] [63b1988d-0355-4dfc-91a0-8a605664721c] [34]
2017/11/14 18:19:01 [SESSION_DELETED] [my-ip] [172.1.0.25:4445] [63b1988d-0355-4dfc-91a0-8a605664721c]
```

**Comment by ryanlevell** [comment]
Just one. I was looking to use an Autoscaling group in AWS. I would probably have ~5 hubs running at a minimum. Then maybe up to 10-15. Should I just use a smaller subnet, like `/28`? This would be 16 IPs and the wait for a session when at 5 of 16 may still take >1 minute.

**Comment by vania-pooh** [comment]
@ryan-levell-twc we are planning to implement running Selenoid on top of Amazon ECS soon. Probably this could help. Also some guys are starting all the stack - Ggr + Selenoids on demand using Amazon Cloud Formation.

**Comment by ryanlevell** [comment]
Thanks @vania-pooh I'll check that out.
