### ISSUE TITLE
Wildcard or "not" for browser name and browser version

### ISSUE THREAD

**Issue by ryanlevell** [aerokube/ggr#134]
Cloud providers have a huge set of platforms. I am looking to use Ggr + an internal grid for a few browsers, but I want everything else passed off to a cloud provider.

I believe the quota file or even `sctl` would be difficult to maintain 100s of browsers from a cloud provider.

As an example, say I want all Firefox `55.0` tests to be ran on an internal grid. Anything that does not match that should be handed off to a cloud provider (e.g. mobile tests).

Initially I was thinking a wildcard:
```
<browser name="*" defaultVersion="latest">
  <version number="*">
    <region name="cloud-provider-1">
      <host name="cloud-provider.com" port="4444" count="1" username="abc" password="123"></host>
```

But that would also incorrectly pass Firefox `55.0` to the cloud provider. So I believe a wildcard would be required with some kind of exclude attribute or tag:
```
<browser name="*" defaultVersion="latest">
  <exclude name="firefox" version="55.0">
  <version number="*">
    <region name="cloud-provider-1">
      <host name="cloud-provider.com" port="4444" count="1" username="abc" password="123"></host>
```

Open to other ideas, this is just an example of what I am trying to solve.

**Comment by vania-pooh** [comment]
Summon @aandryashin.
