### ISSUE TITLE
REST API for GGR

### ISSUE THREAD

**Issue by rab2215** [aerokube/ggr#149]
Are there any other REST endpoints other than /ping for getting information from GGR?  Since GGR does not have a UI, it would be nice to have some way of getting info on the state of GGR's current configuration in regards to browsers available, quotas, etc.

**Comment by vania-pooh** [comment]
1) Ggr has no state - thus no API. :) What is the purpose of getting browser information from the outside? All this information is available in quota files.
2) However in addition to Selenium API Ggr has host API, video proxying API and VNC proxying API. Further reading:
* http://aerokube.com/ggr/latest/#_getting_host_by_session_id
* http://aerokube.com/ggr/latest/#_proxying_vnc_traffic
* http://aerokube.com/ggr/latest/#_proxying_session_video

**Comment by rab2215** [comment]
True, the quota files contain all the information I'm looking for but a "user" wouldn't necessarily have access to this file to know whats available.  I was looking to create a UI component that would show the current configuration.

**Comment by vania-pooh** [comment]
Which information do you need then in such API?

**Comment by rab2215** [comment]
It would be awesome if all the content of the quota.xml could be returned for each user, but at a minimum at least the browser name, version, and host IP address for each user.

**Comment by vania-pooh** [comment]
@rab2215 how about authentication? Returning this data without auth seems to reveal internal cluster architecture.

**Comment by rab2215** [comment]
Good point, in that case it would likely be best to only return the specific user configuration for an authenticated user and unauthenticated users would get the configuration for guest-enabled quotas (which I admit I haven't used much so I'm not sure of all the functionality here).

**Comment by vania-pooh** [comment]
@aandryashin thoughts?
