### ISSUE TITLE
How to handle multiple selenium versions ?

### ISSUE THREAD

**Issue by tahaykACF** [aerokube/ggr#152]
I'm using the GGR with my own selenium grid, 
for some requirements I need to run multiple versions of selenium (v2.53 & v3.6 for now) 
how can I achieve this logic using GGR?

**Comment by vania-pooh** [comment]
Ggr is fully compatible with any WebDriver protocol. To redirect requests to different grid hubs you can use different versions in quota files (e.g. Chrome "3.6-53.0" and "2.53-53.0") or different users.

**Comment by tahaykACF** [comment]
I see, Thank you for your answer @vania-pooh
