### ISSUE TITLE
ggr returns error if browserName == ""

### ISSUE THREAD

**Issue by yaryabu** [aerokube/ggr#154]
https://github.com/aerokube/ggr/blob/feb1dc991c0c8a01859dcf8de1a3e3765ad5b192/proxy.go#L220

We're using ggr for appium automation. [Appium developers ask to leave browserName capability empty](https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/caps.md) if app automation is used, but ggr returns error in this case.

**Comment by vania-pooh** [comment]
Probably could also consider `app` capability.

**Comment by leorush** [comment]
Maybe better way is to add special browser name to selenoid? 
I.e. if name is "empty" selenoid is setting  browserName to empty string.

**Comment by yaryabu** [comment]
I think using only deviceName should be enough. It's not really well documented so most of the times it's just "Android", "iPhone Simulator", "Android Emulator".
