### ISSUE TITLE
[Discussion] Quota with Mongodb

### ISSUE THREAD

**Issue by theredfish** [aerokube/ggr#160]
Hello,

At Oui Technologies we would like to manage quota from a MongoDB (docker container). We see some improvements / possibilities : 

- Ease of quota updating
- Shared database across multiple containers (swarm stack for example)
- Use a web API to manage quota (CRUD operations)

Before we begin, we would like to know if you are interested? We prefer to contribute to the project rather than forking it and keep a version on our side.

**Comment by vania-pooh** [comment]
@theredfish no, we will not accept any database integration. We prefer to keep things simple. You could store quota everywhere and just convert them to Ggr quota files format when needed. So far as Ggr reload configuration without restart this will work like a charm. For example, a similar approach is used in [sctl](http://github.com/seleniumkit/sctl).

**Comment by theredfish** [comment]
@vania-pooh thank you for your answer. Sctl is interesting I will give it a try 👍.
