### ISSUE TITLE
Can't get quota for user

### ISSUE THREAD

**Issue by qwez** [aerokube/ggr#165]
Try to get quota for user "test":
curl -s http://test:test-password@example.com:4444/quota
but got:
404 page not found

test:test-password are correct, because "/host" request works fine:
curl -s http://test:test-password@example.com:4444/host/test-session-id

**Comment by vania-pooh** [comment]
This in not yet released. Should work with `aerokube/ggr:latest` image.

**Comment by vania-pooh** [comment]
Released in https://github.com/aerokube/ggr/releases/tag/1.5.0.
