### ISSUE TITLE
Proxying of vnc traffic from selenoid doesn't work

### ISSUE THREAD

**Issue by qwez** [aerokube/ggr#178]
Steps:
1. configure qouta: `<host name="selenoid_host" port="4444" count="5" vnc="ws://selenoid_host:4444/vnc"/>`
2. Start driver `driver = webdriver.Remote(command_executor='http://ggr_host:4444/wd/hub')`
3. Get session id (ggr_session_id = driver.session_id)
4. Try to get vnc traffic: `ws://ggr_host:4444/vnc/<ggr_session_id>`

Actual:
`Failed to connect to server`
Logs:
`[PROXYING_TO_VNC] [081ed18e890a2cb1f992953ba8276c39b1ecbcf953f91f210ed46765d685a58b] [ws://selenoid_host:4444/vnc/081ed18e890a2cb1f992953ba8276c39b1ecbcf953f91f210ed46765d685a58b]`

081ed18e890a2cb1f992953ba8276c39b1ecbcf953f91f210ed46765d685a58b is ggr_session_id
So, ggr is trying to proxy from ws://selenoid_host:4444/vnc/<ggr_session_id>

Expected:
I think ggr should proxy from ws://selenoid_host:4444/vnc/<selenoid_session_id>
where selenoid_session_id is what we can get here - http://selenoid_host:4444/status
Because ws://selenoid_host:4444/vnc/<selenoid_session_id> works fine

**Comment by vania-pooh** [comment]
@qwez 
1) Ggr `/vnc/` API returns a web-socket.
2) I'm seeing in your quota Selenoid port is 4445 and in logs - it is 4444.

**Comment by qwez** [comment]
1. Why ws://selenoid_host:4444/vnc/<selenoid_session_id> works, and ws://ggr_host:4444/vnc/<ggr_session_id> doesn't?
2. Fix, port is 4444

**Comment by vania-pooh** [comment]
Still investigating. Probably you are right. This feature has never been used in production.

**Comment by vania-pooh** [comment]
@qwez should work with `aerokube/selenoid:latest`.

**Comment by qwez** [comment]
@vania-pooh can you make a release (not a docker)?

**Comment by vania-pooh** [comment]
@qwez released  as `1.5.1`. Available in Docker Hub as `aerokube/selenoid:1.5.1`.
