### ISSUE TITLE
/etc/grid-router/users.htpasswd" does not exist

### ISSUE THREAD

**Issue by superTes** [aerokube/ggr#179]
Your tutorial was used (http://aerokube.com/ggr/latest/)

When i try to start ggr i get error
```sh
2018/03/16 13:46:40 [-] [-] [INIT] [-] [-] [-] [-] [-] [-] [Users file is "/etc/grid-router/users.htpasswd"]
2018/03/16 13:46:40 [-] [-] [INIT] [-] [-] [-] [-] [-] [-] [Users file "/etc/grid-router/users.htpasswd" does not exist]
```

```cat ```
```sh
test:$apr1$NwA7j5SE$v.x4qnZ3YWB/HudujM2tJ0
```

**Comment by vania-pooh** [comment]
@superTes does it exist in container?

**Comment by superTes** [comment]
@vania-pooh i got this error when trying to run container 
```
docker run my-container-id
2018/03/16 13:46:40 [-] [-] [INIT] [-] [-] [-] [-] [-] [-] [Users file is "/etc/grid-router/users.htpasswd"]
2018/03/16 13:46:40 [-] [-] [INIT] [-] [-] [-] [-] [-] [-] [Users file "/etc/grid-router/users.htpasswd" does not exist]
```

**Comment by vania-pooh** [comment]
@superTes what is the exact command you are using to start Ggr?

**Comment by vania-pooh** [comment]
@superTes any more stuff to investigate here?

**Comment by LiPhynd** [comment]
@vania-pooh , I have the same issue trying to start Ggr. I am using Docker start -i  89baf91157e8

Step to reproduce the issue:
Start  Ggr container with below com
 > docker run -d --name \
    ggr -v /etc/grid-router/:/etc/grid-router:ro \
    --net host aerokube/ggr:latest-release

> Docker start -i 89baf91157e8

![image](https://user-images.githubusercontent.com/45089149/72232790-676dca80-3591-11ea-95d0-9a565618425c.png)

Open http://test:test-password@localhost:4444/wd/hub/
![image](https://user-images.githubusercontent.com/45089149/72232839-ab60cf80-3591-11ea-87e0-930f6699ae99.png)
