### ISSUE TITLE
The way to get the driver on the right OS

### ISSUE THREAD

**Issue by guskovd** [aerokube/ggr#190]
For example, I have 2 nodes: on Linux and on Windows.
```xml
<qa:browsers xmlns:qa="urn:config.gridrouter.qatools.ru">
<!-- My Linux node -->
<browser name="firefox" defaultVersion="59.0">
    <version number="59.0">
        <region name="1">
            <host name="10.0.0.1" port="4444" count="1"/> 
        </region>
    </version>
</browser>
<!-- My Windows node -->
<browser name="firefox" defaultVersion="59.0">
    <version number="59.0">
        <region name="1">
            <host name="10.0.0.2" port="4444" count="1"/> 
        </region>
    </version>
</browser>
</qa:browsers>
```
I would like to receive a driver on a specific OS. Can this be done by means of ggr?
Tried to do this via platform capability. But it does not work

**Comment by vania-pooh** [comment]
@guskovd we are using different versions, e.g. `win-59.0` and `linux-59.0`.

**Comment by guskovd** [comment]
I also used this method for a long time. But this does not work with the latest versions of geckodriver

**Comment by guskovd** [comment]
in my case:
```python
from selenium import webdriver
capabilities = {'browserName': 'firefox', 'version': 'w59.0.2'}
driver = webdriver.Remote("http://10.0.0.1:4444/wd/hub", desired_capabilities=capabilities)
```
generates an error:
```bash
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities
```
That is, with ggr all is well. But geckodriver does not work with similar versions

**Comment by vania-pooh** [comment]
@guskovd need to think more about it.

**Comment by guskovd** [comment]
Any ideas?

**Comment by vania-pooh** [comment]
@guskovd I would add optional `platform` field to `version` tag.

**Comment by vania-pooh** [comment]
Should consider both `platform` and `platformName` capabilities (https://www.w3.org/TR/webdriver/#capabilities) according to spec.
