### ISSUE TITLE
Allow for blank window names.

### ISSUE THREAD

**Issue by skunkworker** [aerokube/ggr#194]
Selenium allows for blank/null window names when resizing, if left blank the current window is used. `ggr` seems to think that `session/{{session_id}}/window//size` is invalid because of the double `//` and changes it to be `session/{{session_id}}/window/size` and then selenium throws a 404.

**Comment by vania-pooh** [comment]
Need to investigate it. Basically for every request except `POST /wd/hub/session` Ggr just proxies everything to upstream host.
