### ISSUE TITLE
Capability to set max request timeout

### ISSUE THREAD

**Issue by vania-pooh** [aerokube/ggr#195]
Should be no more than `-max-timeout` value.

**Comment by vania-pooh** [comment]
Does not make sense. It is better to adjust client timeout and allow client disconnect logic to work.

**Comment by KathiresanRamkumar95** [comment]
After setting the client(selenoid) timeout to allow the disconnect after the max request timeout, GGR does not affect the client(Selenoid) to disconnect that.

If I using selenoid separately it works fine. After configuring with GGR doesn't work

Help to solve this

@vania-pooh

**Comment by vania-pooh** [comment]
@KathiresanRamkumar95 ggr just proxies everything to Selenoid. Just adjust client disconnect timeout in Nginx being installed ahead of Ggr.
