### ISSUE TITLE
GGr can not start firefox vnc session

### ISSUE THREAD

**Issue by kenlma** [aerokube/ggr#202]
hi
when i use ggr start firefox vnc session. i got an error and can not start the session. i tried to look for browser container log, but the container is gone fast.
Also tried ggr start firefox without vnc, it's work well. ggr start Chrome&vnc both work well
any idea?

log:
cannot create session firefox-vnc_58.0 on any hosts after 1 attempt(s), last host error was: Requested environment is not available (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 1.20 seconds

ggr log
2018/05/16 14:34:35 [0] [0.00s] [SESSION_ATTEMPTED] [test] [ip] [firefox-vnc_58.0] [ip] [-] [1] [-]
2018/05/16 14:34:36 [0] [1.15s] [SESSION_FAILED] [test] [ip] [firefox-vnc_58.0] [172.16.139.27:8081] [-] [1] [Requested environment is not available]
2018/05/16 14:34:36 [0] [1.15s] [SESSION_NOT_CREATED] [test] [ip] [firefox-vnc_58.0] [-] [-] [-] [-]

selenoid node log
2018/05/16 14:34:35 [297671] [LOCATING_SERVICE] [firefox] [vnc_58.0]
2018/05/16 14:34:35 [297671] [USING_DOCKER] [firefox] [vnc_58.0]
2018/05/16 14:34:35 [297671] [CREATING_CONTAINER] [selenoid/vnc:firefox_58.0]
2018/05/16 14:34:35 [297671] [STARTING_CONTAINER] [selenoid/vnc:firefox_58.0] [caa5aa0cc580142ad2bc9e5709fdd66550de05fb39c1480a3efa70fb1ba4776c]
2018/05/16 14:34:35 [297671] [CONTAINER_STARTED] [selenoid/vnc:firefox_58.0] [caa5aa0cc580142ad2bc9e5709fdd66550de05fb39c1480a3efa70fb1ba4776c] [0.20s]
2018/05/16 14:34:36 [297671] [SERVICE_STARTED] [selenoid/vnc:firefox_58.0] [caa5aa0cc580142ad2bc9e5709fdd66550de05fb39c1480a3efa70fb1ba4776c] [0.15s]
2018/05/16 14:34:36 [297671] [PROXY_TO] [caa5aa0cc580142ad2bc9e5709fdd66550de05fb39c1480a3efa70fb1ba4776c] [http://192.168.0.3:4444/wd/hub]
2018/05/16 14:34:36 [297671] [SESSION_ATTEMPTED] [http://192.168.0.3:4444/wd/hub] [1]
2018/05/16 14:34:36 [297671] [SESSION_FAILED] [http://192.168.0.3:4444/wd/hub] [400 Bad Request]
2018/05/16 14:34:36 [297671] [REMOVING_CONTAINER] [caa5aa0cc580142ad2bc9e5709fdd66550de05fb39c1480a3efa70fb1ba4776c]
2018/05/16 14:34:36 [297671] [CONTAINER_REMOVED] [caa5aa0cc580142ad2bc9e5709fdd66550de05fb39c1480a3efa70fb1ba4776c]

**Comment by kenlma** [comment]
seems firefox regular image already included vnc feature. i just use the regular image and enable vnc. i can see the screen display in selenoid ui

**Comment by vania-pooh** [comment]
@kenlma yes, no need to include `vnc` keyword in browser version capability.
