### ISSUE TITLE
Unable to create new service: ChromeDriverService

### ISSUE THREAD

**Issue by timothyjmtan** [aerokube/ggr#204]
Hi, my current set up is like this (in AWS):

Each of the below is an individual EC2 instance :
- test trigger (the container running the 'mvn verify' command)
- go-grid-router  (running with guest username 'test')
- Selenium Hub + Node (both hosted on the same EC2 instance)

I currently see the requests being forwarded like so:
Test Trigger -> GGR -> Selenium hub -> Selenium node

However, I am getting the following error:

Logs from 'mvn verify' commands
```java
Caused by: org.openqa.selenium.WebDriverException: cannot create session chrome-65.0 on any hosts after 1 attempt(s), last host error was: Unable to create new service: ChromeDriverService
```

GGR Logs
```java Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:33:15.31Z'
 System info: host: 'ip-10-116-144-255', ip: 'Unknown', os.name: 'Linux', os.arch: 'amd64', os.version: '4.14.33-51.37.amzn1.x86_64', java.version: '1.8.0_171'
 Driver info: driver.version: unknown]
 2018/05/17 09:25:32 [95] [0.01s] [SESSION_NOT_CREATED] [test] [10.116.145.250] [chrome-65.0] [-] [-] [-] [-]
 2018/05/17 09:25:32 [96] [0.00s] [SESSION_ATTEMPTED] [test] [10.116.145.250] [chrome-65.0] [10.116.144.255:4444] [-] [1] [-]
 2018/05/17 09:25:32 [96] [0.01s] [SESSION_FAILED] [test] [10.116.145.250] [chrome-65.0] [10.116.144.255:4444] [-] [1] [Unable to create new service: ChromeDriverService
```

Node Logs:
```java
09:25:32.340 INFO [ActiveSessionFactory.apply] - Capabilities are: Capabilities {acceptInsecureCerts: true, acceptSslCerts: true, browserName: chrome, goog:chromeOptions: {args: [--disable-gpu, --headless, --window-size=1440,2560, --single-process, --no-sandbox, --user-data-dir=/tmp/user-data, --data-path=/tmp/data-path, --homedir=/tmp, --disk-cache-dir=/tmp/cache..., --ignore-certificate-errors, --acceptInsecureCerts=true, --allow-running-insecure-co...]}, version: 65.0}
09:25:32.340 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDriverService)
```

test.xml
```json
<qa:browsers xmlns:qa="urn:config.gridrouter.qatools.ru">
<browser name="chrome" defaultVersion="65.0">
    <version number="65.0">
        <region name="1">
            <host name="10.116.144.255" port="4444" count="1"/>
        </region>
    </version>
</browser>
</qa:browsers>
```

nodeConfig.xml
```json
{
  "capabilities": [
    {
      "browserName": "chrome",
      "maxInstances": 100,
      "platform": "LINUX",
      "seleniumProtocol": "WebDriver",
      "webdriver.chrome.driver": "/home/ec2-user/headless/resources/lib/chromedriver",
      "version": "65.0"
    }
  ],
    "_comment" : "Configuration for Node",
    "cleanUpCycle": 2000,
    "timeout": 30000,
    "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
    "port": 5555,
    "hub": "http://10.116.144.255:4444/grid/register",
    "register": true,
    "maxSession": 100
}
```

I have seen from other tickets that one potential point of failure is the 'chrome version' string mismatch between the quota file with the nodeConfig.json file. However, mine seems to be correct (as seen above).

The same Chrome libs/binaries, nodeConfig.json, hubConfig.json work on a 'traditional' Selenium Grid setup.

Do I actually need to have a binary file called 'chrome-65.0'? Currently my binary is just 'chrome'.

**Comment by vania-pooh** [comment]
@timothyjmtan Ggr does not modify initial user request. Just try to create a new session by going directly to your Selenium hub `10.116.144.255:4444` and you will get the same error. Ggr just returns you this error. No need to rename `chromedriver` on the hub side and your JSON seems to be correct (hub should have `browserName=chrome, version = 65.0` as specified in XML quota file).

The real reason of the error could be e.g. missing execution permissions for `Chromedriver` or issues with Chrome Sandbox binary (should have particular permissions). Please confirm that it fails when going directly to the hub.

**Comment by timothyjmtan** [comment]
@vania-pooh  Thanks for the quick reply!

I also initially suspected that the issue might have been due to permissions for chrome or chromedriver, so we gave a chdmod -R 777 to its parent directory. However it doesn't seem to resolve the issue:

```
[ec2-user@ip-10-116-144-255 chromedriver]$ ls -ltrs
total 213596
  4092 -rwxrwxrwx 1 ec2-user ec2-user   4189360 Dec  1 15:11 libosmesa.so
  7720 -rwxrwxrwx 1 ec2-user ec2-user   7903592 Jan  9 18:35 chromedriver
100184 -rwxrwxrwx 1 ec2-user ec2-user 102584712 Feb 15 10:13 chrome
   448 -rwxrwxrwx 1 ec2-user ec2-user    458144 Feb 19 08:28 libORBit-2.so.0
   964 -rwxrwxrwx 1 ec2-user ec2-user    983882 Feb 19 08:28 libgconf-2.so.4
     4 drwxrwxrwx 2 ec2-user ec2-user      4096 May 17 07:23 locales
```

Thanks for the confirmation that its not a ggr issue and instead is probably on Selenium Grid's side. I'll remove the dependency on ggr and further debug from there.

**Comment by vania-pooh** [comment]
@timothyjmtan I would recommend to take a look at Chrome windows if that's possible. Sometimes it shows an error message - why it can not start.

**Comment by timothyjmtan** [comment]
Thanks will try that.

In the quota file, is it necessary to define the defaultVersion="65.0" as well as the xml tags for <version number="65.0">, or are we able to remove those?

**Comment by vania-pooh** [comment]
@timothyjmtan `defaultVersion` is used only when you have neither `browserVersion` nor `version` capability set or it is empty string.

**Comment by timothyjmtan** [comment]
Thank you. I will close this ticket now as my initial question has been answered.
