### ISSUE TITLE
Implementing an AWS ELB over multiple ggr instances

### ISSUE THREAD

**Issue by timothyjmtan** [aerokube/ggr#206]
Hello,

I am trying to add an ELB over 2 ggr instances.

My setup is currently like this:

```
    AWS ELB
     /     \
ggr1        ggr2
   \       /
     hub1
     /   \
node1    node2

```

I have a question regarding the setup for the ELB:

When I create a target group for the ELB to register to, I'm assuming that the target group should contain both ggr1 and ggr2 instance.

I am currently setting them to listen to port 4444 and 80. However both show a warning message:

> None of these Availability Zones contains a healthy target. Requests are being routed to all targets.

Is this expected, or am I listening on the wrong port?

**Comment by aandryashin** [comment]
You can use ggr's /ping as healthy target...

пт, 18 мая 2018 г., 11:19 timothyjmtan <notifications@github.com>:

**Comment by timothyjmtan** [comment]
Perfect thank you! Closing ticket as my issue has been resolved.
