### ISSUE TITLE
Question: Can i restrict a test to a specific region using browserVersion-capability?

### ISSUE THREAD

**Issue by O5ten** [aerokube/ggr#234]
As the topic says, can i provide a capability to select only browsers from a particular region (Say `EXTERNAL` or `INTERNAL` regions if we consider a corporate firewall in the middle).

### Something like this
```Java
remoteWebDriver.addCapability("browserName", "chrome");
remoteWebDriver.addCapability("browserVersion", "68:INTERNAL");
```

Or is there some other way i can accomplish this?

**Comment by vania-pooh** [comment]
@O5ten so far as Ggr is matching version by prefix you need to use it like this:
```
remoteWebDriver.addCapability("browserVersion", "INTERNAL:68");
remoteWebDriver.addCapability("browserVersion", "EXTERNAL:68");
```
Anyway you need to have exactly the same version on the hosts with browsers.

**Comment by O5ten** [comment]
Super! You probably need to document this information more properly as we scoured the docs quite extensively without finding it. I had a look at the source to figure out that it can probably be done. 

IT's also possible we're just poor readers. Thanks! :)
