### ISSUE TITLE
ggr shows error in logs- bind error

### ISSUE THREAD

**Issue by rohitpatwari84** [aerokube/ggr#237]
I am using selenoid with ggr -
After I  install ggr using -
```
 docker run -d --name \
    ggr -v /etc/grid-router/:/etc/grid-router:ro \
    --net host aerokube/ggr:latest-release
```

Seeing the below in logs --
```
root@myhost:/home/docker> docker logs ggr
2018/09/08 09:19:46 [-] [-] [INIT] [-] [-] [-] [-] [-] [-] [Users file is "/etc/grid-router/users.htpasswd"]
2018/09/08 09:19:46 [-] [-] [INIT] [-] [-] [-] [-] [-] [-] [Loading configuration files from "/etc/grid-router/quota"]
2018/09/08 09:19:46 [-] [-] [INIT] [-] [-] [-] [-] [-] [-] [listen tcp :4444: bind: address already in use]
```

**Comment by aandryashin** [comment]
is there selenoid running on the host? you have to start even selenoid or
ggr on differend ports^ use command like the following:

docker run -d --name \
    ggr -p 4445:4444 -v /etc/grid-router/:/etc/grid-router:ro \
    --net host aerokube/ggr:latest-release


сб, 8 сент. 2018 г. в 12:44, rohitpatwari84 <notifications@github.com>:

**Comment by rohitpatwari84** [comment]
yes @aandryashin  , I did that . And now ggr works fine . But somehow not able to see my tests on selenoid ui . I linked selenoid ui to ggr-ui . And ggr-ui is tied to xml file in quota directory . And there it is linked to selenoid . But seems ggr-ui is unable to connect to selenoid for status ( Although my tests run fine) -

ggr-ui logs show --
2018/09/08 11:31:14 [STATUS] [Failed to fetch status: Get http://localhost:4445/status: dial tcp 127.0.0.1:4445:

**Comment by rohitpatwari84** [comment]
Closed this in another thread . Replacing localhost with <actual IP of docker host> worked!!
