### ISSUE TITLE
quota files per user?

### ISSUE THREAD

**Issue by rohitpatwari84** [aerokube/ggr#238]
If I have 100 users using my selenoid cluster.Do I have to create 100 user files.Isnt there any better way to avoid so much duplication?Or I should create files as per groups and assign multiple users a single quota file?Although in that case too the groups might increase and so the files

**Comment by vania-pooh** [comment]
@rohitpatwari84 two possible answers:
1) We are using Ggr users mainly as per-team accounts, i.e. we give a pair of user\password to a team, not to every distinct person.
2) We also have a tool called [sctl](https://github.com/seleniumkit/sctl) allowing to generate XML quota files from more compact JSON definition.

**Comment by rohitpatwari84** [comment]
Ok thanks @vania-pooh . I think second one is a good option. We can also build a small UI utility which will accept the fields in a user friendly way and create a xml for us.

**Comment by rohitpatwari84** [comment]
Thanks @vania-pooh. I will take a look at sclt.
