### ISSUE TITLE
Unable to start a WebDriver session.

### ISSUE THREAD

**Issue by yosserO** [aerokube/ggr#239]
Hi guys,

I really don't know if this is a bug or if I'm doing something wrong.

I'm trying to start ggr with the user listed in the tutorial:

`htpasswd -bc /etc/grid-router/users.htpasswd test test-password
`

My quota file is named test.xml and looks like this

`<qa:browsers xmlns:qa="urn:config.gridrouter.qatools.ru">
<browser name="chrome" defaultVersion="68.0">
    <version number="68.0">
        <region name="vm1">
            <host name="ip-address-of-host" port="4445" count="2"/>
        </region>
    </version>
</browser>
</qa:browsers>
`

I'm running Selenoid on the host and the Selenoid-UI is showing chrome 68.0 under the available capabilities.

When I start the tests I m getting this error:

`E/runner - Unable to start a WebDriver session.
[chrome #01-11] (node:10776) UnhandledPromiseRejectionWarning: WebDriverError: cannot create session chrome-68.0 on any hosts after 1 attempt(s)
[chrome #01-11]     at Object.checkLegacyResponse (AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\error.js:546:15)
[chrome #01-11]     at parseHttpResponse (AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\http.js:509:13)
[chrome #01-11]     at doSend.then.response (AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\http.js:441:30)
[chrome #01-11]     at <anonymous>
[chrome #01-11]     at process._tickCallback (internal/process/next_tick.js:189:7)
[chrome #01-11] (node:10776) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
[chrome #01-11] (node:10776) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[chrome #01-11] [14:21:27] I/runnerCli - cannot create session chrome-68.0 on any hosts after 1 attempt(s)
`

Thanks!!!

**Comment by vania-pooh** [comment]
@yosserO is your Selenoid host listening on port 4445? Browsers file seems to be correct.

**Comment by yosserO** [comment]
Good Point!! It was listening on port 4444 :/

**Comment by yosserO** [comment]
@vania-pooh Thanks for your help !!

I have some questions:
- Is there a possiblity to specify the max number of browsers that can be run on a host? The only way I m seeing is by setting the browser maxInstances in the test. I would like to set this property for each host sperately.
- Is there a Selenoid Slack Channel for Support?

**Comment by vania-pooh** [comment]
@yosserO 
1) Ggr has no way to limit browser consumption because it has no internal state. You have to limit such consumption on the hosts where browsers reside. E.g. when using Selenoid this can be delivered by changing `-limit` flag. All requests on top of this limit are queued.
2) We only have Telegram support channel https://t.me/aerokube You can also ask questions by email: support@aerokube.com
