### ISSUE TITLE
Add documentation about using Ggr with Appium

### ISSUE THREAD

**Issue by vania-pooh** [aerokube/ggr#242]
As described.

**Comment by sharathkonda** [comment]
> As described.
Hi Team,
The <user>.xml is referencing with the browser. Should I assume that mobile support is work in progress?
I have not tested by changing from the browser name from firefox/chrome to Emulator or simulator.

**Comment by vania-pooh** [comment]
@sharathkonda mobile support works.

**Comment by sharathkonda** [comment]
Hi @vania-pooh 
Thanks for the message.
I was passing the deviceName in the name attribute of the browser and it was contacting the relevant hub.
Now I got a peculiar situation where  I have to send the desired capabilities with deviceName as one type of Emulator while browserName as a Chrome browser so that it can test the browser on a mobile device ie..testing Chrome browser in a mobile emulator.

Do you have any idea how to make this work?
Thanks in advance.

**Comment by sharathkonda** [comment]
Sorry If I am sending in the wrong issue:
Hi @vania-pooh 
My desired capabilities is:
"desiredCapabilities": {
"newCommandTimeout": "5000",
"platformVersion": "8.0",
"browserName": "chrome",
"platformName": "Android",
"deviceName": "GalaxyS7",
"version": "68.0",
"applicationName": "GalaxyS7"
}


I tried both the xml elements:
<browser name="chrome" defaultVersion="68.0">
    <version number="68.0">
        <region name="1">
            <host name="PKXSWD55330001S.ext.corp" port="4446" count="1"/>
        </region>
    </version>
</browser>
<browser name="GalaxyS7" defaultVersion="8.0">
    <version number="8.0">
        <region name="1">
            <host name="PKXSWD55330001S.ext.corp" port="4446" count="1"/>
        </region>
    </version>
</browser>

**Comment by vania-pooh** [comment]
@sharathkonda did you reload Ggr configuration after modifying it? Config seems to be ok.

**Comment by sharathkonda** [comment]
Hi @vania-pooh 
I reloaded the ggr configuration.
My query is, if I want to use the chrome browser in an Android mobile,
what should be the xml settings for that user?

My desired capabilities for that (basically it contains browserName and deviceName):
My desired capabilities is:
"desiredCapabilities": {
"newCommandTimeout": "5000",
"platformVersion": "8.0",
"browserName": "chrome",
"platformName": "Android",
"deviceName": "GalaxyS7",
"version": "68.0",
"applicationName": "GalaxyS7"
}
