### ISSUE TITLE
Not able to set up GGR in mac with Cloud Service

### ISSUE THREAD

**Issue by DeChrish** [aerokube/ggr#263]
@vania-pooh  I have installed the docker/ selenoid and added cloud service.
I have not changed the test.xml file name, can you help us to install in right way to execute the test in cloud service.

Step 1 :  Install docker
Step 2 : $ mkdir -p /etc/grid-router/quota
Step 3 : htpasswd -bc /etc/grid-router/users.htpasswd test test-password
Step 4 : curl -s https://aerokube.com/cm/bash | bash
Step 5 :  ./cm selenoid start --vnc --port 4445
Step 6 :  docker run -d --name ggr -v /etc/grid-router/:/etc/grid-router:ro  --net host aerokube/ggr:latest-release

Step 7 : http://test:test-password@localhost:4444/wd/hub

/etc/grid-router/quota/test.xml
`
<qa:browsers xmlns:qa="urn:config.gridrouter.qatools.ru">
<browser name="chrome" defaultVersion="70.0">
    <version number="70.0">
        <region name="1">
           <host name="ondemand.saucelabs.com" port="443" count="1" username="saucelabs-id" password="saucelabs-password" scheme="https" />
        </region>
    </version>
</browser>
</qa:browsers>
`

**Comment by vania-pooh** [comment]
@DeChrish which error message are you receiving? What's inside Ggr logs?

**Comment by vania-pooh** [comment]
@DeChrish that means for some reason Ggr is not listening on port 4444. Is Ggr container running? What is the output of `docker logs ggr` command?

**Comment by DeChrish** [comment]
@vania-pooh yes container is not stable -- 
CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS                        PORTS                    NAMES
43aa02cc65b1        aerokube/ggr:latest-release   "/usr/bin/ggr -liste…"   6 minutes ago       Exited (255) 52 seconds ago                            ggr

**Comment by vania-pooh** [comment]
@DeChrish need log message inside container that causes Ggr to stop. Without it can't diagnose.

**Comment by DeChrish** [comment]
@vania-pooh 

/p/e/g/quota docker logs ggr                                                                                                                                      11:35:59
2019/01/05 20:09:45 [-] [-] [INIT] [-] [-] [-] [-] [-] [-] [Users file is "/etc/grid-router/users.htpasswd"]
2019/01/05 20:09:45 [-] [-] [INIT] [-] [-] [-] [-] [-] [-] [Loading configuration files from "/etc/grid-router/quota"]
⋊> /p/e/g/quota docker logs ggr                                                                                                                                      11:36:00
2019/01/05 20:09:45 [-] [-] [INIT] [-] [-] [-] [-] [-] [-] [Users file is "/etc/grid-router/users.htpasswd"]
2019/01/05 20:09:45 [-] [-] [INIT] [-] [-] [-] [-] [-] [-] [Loading configuration files from "/etc/grid-router/quota"]
⋊> /p/e/g/quota docker logs ggr                                                                                                                                      11:36:19
2019/01/05 20:09:45 [-] [-] [INIT] [-] [-] [-] [-] [-] [-] [Users file is "/etc/grid-router/users.htpasswd"]
2019/01/05 20:09:45 [-] [-] [INIT] [-] [-] [-] [-] [-] [-] [Loading configuration files from "/etc/grid-router/quota"]
⋊> /p/e/g/quota docker logs ggr                                                                                                                                      11:36:24
2019/01/05 20:09:45 [-] [-] [INIT] [-] [-] [-] [-] [-] [-] [Users file is "/etc/grid-router/users.htpasswd"]
2019/01/05 20:09:45 [-] [-] [INIT] [-] [-] [-] [-] [-] [-] [Loading configuration files from "/etc/grid-router/quota"]
⋊> /p/e/g/quota docker logs ggr                                                                                                                                      11:36:26
2019/01/05 20:09:45 [-] [-] [INIT] [-] [-] [-] [-] [-] [-] [Users file is "/etc/grid-router/users.htpasswd"]
2019/01/05 20:09:45 [-] [-] [INIT] [-] [-] [-] [-] [-] [-] [Loading configuration files from "/etc/grid-router/quota"]
⋊> /p/e/g/quota docker logs ggr                                                                                                                                      11:36:30
2019/01/05 20:09:45 [-] [-] [INIT] [-] [-] [-] [-] [-] [-] [Users file is "/etc/grid-router/users.htpasswd"]
2019/01/05 20:09:45 [-] [-] [INIT] [-] [-] [-] [-] [-] [-] [Loading configuration files from "/etc/grid-router/quota"]
⋊> /p/e/g/quota                                                                                                                                                      11:36:50

**Comment by vania-pooh** [comment]
@DeChrish according to the log Ggr is working. If it stops it should either print a stack trace (in case of bugs) or something like:
```
[-] [30s] [SHUTTING_DOWN] [-] [-] [-] [-] [-] [-] [-]
```
If you still can't connect to Ggr it seems to be MacOS port forwarding problem.

**Comment by DeChrish** [comment]
@sskorol will your scrip help to fix the problem?

```
#!/bin/bash
docker run -d --name selenoid -p 4445:4444 -v /etc/selenoid:/etc/selenoid:ro -v /var/run/docker.sock:/var/run/docker.sock aandryashin/selenoid:latest
ip=`docker inspect --format {{.NetworkSettings.IPAddress}} selenoid`
xml ed --inplace -u '//host/@name' -v "$ip" /etc/grid-router/quota/username.xml
docker run -d --name ggr -p 4444:4444 -v /etc/grid-router/:/etc/grid-router:ro aandryashin/ggr
```

**Comment by DeChrish** [comment]
@vania-pooh after using the above script, am getting bad-capability error. Pl check ggr logs

```
 /p/e/grid-router docker logs ggr                                                                                                                                  10:39:29
2019/01/07 18:37:35 [-] [-] [INIT] [-] [-] [-] [-] [-] [-] [Users file is "/etc/grid-router/users.htpasswd"]
2019/01/07 18:37:35 [-] [-] [INIT] [-] [-] [-] [-] [-] [-] [Loading configuration files from "/etc/grid-router/quota"]
2019/01/07 18:38:51 [-] [-] [BAD_CAPABILITY] [Using default value for capability browserName: should be a string or a map but is <nil>] [-] [-] [-] [-] [-] [-]
2019/01/07 18:38:51 [-] [-] [BAD_CAPABILITY] [Using default value for capability version: should be a string or a map but is <nil>] [-] [-] [-] [-] [-] [-]
2019/01/07 18:38:51 [-] [-] [BAD_CAPABILITY] [Using default value for capability platform: should be a string or a map but is <nil>] [-] [-] [-] [-] [-] [-]
2019/01/07 18:38:51 [-] [-] [BAD_CAPABILITY] [Using default value for capability labels: should be a string or a map but is <nil>] [-] [-] [-] [-] [-] [-]
2019/01/07 18:38:51 [-] [-] [BAD_CAPABILITY] [Using default value for capability labels: should be a string or a map but is <nil>] [-] [-] [-] [-] [-] [-]
2019/01/07 18:38:51 [0] [0.00s] [UNSUPPORTED_BROWSER] [c792401] [172.17.0.1] [chrome-70.0] [-] [-] [-] [-]
2019/01/07 18:38:51 [-] [-] [BAD_CAPABILITY] [Using default value for capability browserName: should be a string or a map but is <nil>] [-] [-] [-] [-] [-] [-]
2019/01/07 18:38:51 [-] [-] [BAD_CAPABILITY] [Using default value for capability version: should be a string or a map but is <nil>] [-] [-] [-] [-] [-] [-]
2019/01/07 18:38:51 [-] [-] [BAD_CAPABILITY] [Using default value for capability platform: should be a string or a map but is <nil>] [-] [-] [-] [-] [-] [-]
2019/01/07 18:38:51 [-] [-] [BAD_CAPABILITY] [Using default value for capability labels: should be a string or a map but is <nil>] [-] [-] [-] [-] [-] [-]
2019/01/07 18:38:51 [-] [-] [BAD_CAPABILITY] [Using default value for capability labels: should be a string or a map but is <nil>] [-] [-] [-] [-] [-] [-]
2019/01/07 18:38:51 [1] [0.00s] [UNSUPPORTED_BROWSER] [c792401] [172.17.0.1] [chrome-70.0] [-] [-] [-] [-]
2019/01/07 18:41:26 [-] [-] [BAD_CAPABILITY] [Using default value for capability browserName: should be a string or a map but is <nil>] [-] [-] [-] [-] [-] [-]
2019/01/07 18:41:26 [-] [-] [BAD_CAPABILITY] [Using default value for capability browserName: should be a string or a map but is <nil>] [-] [-] [-] [-] [-] [-]
2019/01/07 18:41:26 [-] [-] [BAD_CAPABILITY] [Using default value for capability deviceName: should be a string or a map but is <nil>] [-] [-] [-] [-] [-] [-]
2019/01/07 18:41:26 [-] [-] [BAD_CAPABILITY] [Using default value for capability deviceName: should be a string or a map but is <nil>] [-] [-] [-] [-] [-] [-]
2019/01/07 18:41:26 [-] [-] [BAD_CAPABILITY] [Using default value for capability version: should be a string or a map but is <nil>] [-] [-] [-] [-] [-] [-]
2019/01/07 18:41:26 [-] [-] [BAD_CAPABILITY] [Using default value for capability platform: should be a string or a map but is <nil>] [-] [-] [-] [-] [-] [-]
2019/01/07 18:41:26 [-] [-] [BAD_CAPABILITY] [Using default value for capability labels: should be a string or a map but is <nil>] [-] [-] [-] [-] [-] [-]
2019/01/07 18:41:26 [-] [-] [BAD_CAPABILITY] [Using default value for capability labels: should be a string or a map but is <nil>] [-] [-] [-] [-] [-] [-]
2019/01/07 18:41:26 [2] [0.00s] [BROWSER_NOT_SET] [c792401] [172.17.0.1] [-] [-] [-] [-] [-]
2019/01/07 18:41:26 [-] [-] [BAD_CAPABILITY] [Using default value for capability browserName: should be a string or a map but is <nil>] [-] [-] [-] [-] [-] [-]
2019/01/07 18:41:26 [-] [-] [BAD_CAPABILITY] [Using default value for capability browserName: should be a string or a map but is <nil>] [-] [-] [-] [-] [-] [-]
2019/01/07 18:41:26 [-] [-] [BAD_CAPABILITY] [Using default value for capability deviceName: should be a string or a map but is <nil>] [-] [-] [-] [-] [-] [-]
2019/01/07 18:41:26 [-] [-] [BAD_CAPABILITY] [Using default value for capability deviceName: should be a string or a map but is <nil>] [-] [-] [-] [-] [-] [-]
2019/01/07 18:41:26 [-] [-] [BAD_CAPABILITY] [Using default value for capability version: should be a string or a map but is <nil>] [-] [-] [-] [-] [-] [-]
2019/01/07 18:41:26 [-] [-] [BAD_CAPABILITY] [Using default value for capability platform: should be a string or a map but is <nil>] [-] [-] [-] [-] [-] [-]
2019/01/07 18:41:26 [-] [-] [BAD_CAPABILITY] [Using default value for capability labels: should be a string or a map but is <nil>] [-] [-] [-] [-] [-] [-]
2019/01/07 18:41:26 [-] [-] [BAD_CAPABILITY] [Using default value for capability labels: should be a string or a map but is <nil>] [-] [-] [-] [-] [-] [-]
2019/01/07 18:41:26 [3] [0.00s] [BROWSER_NOT_SET] [c792401] [172.17.0.1] [-] [-] [-] [-] [-]
```

**Comment by DeChrish** [comment]
@vania-pooh 
Below is my Test Script:
```

import cucumber.api.java.en.Given;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.remote.RemoteWebDriver;

import java.net.MalformedURLException;
import java.net.URL;


public class MyStepDefs {
    WebDriver driver;
  
  @Given("verify page {}")
    public void verifyPage(String url) throws MalformedURLException {
        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability("browserName", "chrome");
        capabilities.setCapability("version", "70.0");
        capabilities.setCapability("platform", "macOS 10.13");
        capabilities.setCapability("seleniumVersion", "3.14.0");
        capabilities.setCapability("build", "testBuild3");
        capabilities.setCapability("name", "queue-test");
        WebDriver driver = new RemoteWebDriver(new URL("http://c792401:96edce-b0e-ba20@localhost:4444/wd/hub"), capabilities);
        driver.get(url);
        driver.quit();
    }
}

```

**Comment by vania-pooh** [comment]
@DeChrish do you have `c792401.xml` file? Because your user name is `c792401` so your quota file should be named `c792401.xml`.

**Comment by DeChrish** [comment]
@vania-pooh  yes i  have  c792401.xml

`
⋊> /p/e/g/quota ls                                                                                                                                                   
c792401.xml
⋊> /p/e/g/quota
`

**Comment by vania-pooh** [comment]
@DeChrish ok, to make sure Ggr reads correct file do the following request:
```
~# curl -s http://c792401:96edce-b0e-ba20@localhost:4444/quota
```
This will print all hosts and browser versions available in quota in JSON format.

**Comment by DeChrish** [comment]
@vania-pooh 

`[{"Name":"","DefaultVersion":"70.0","DefaultPlatform":"","Versions":[{"Number":"70.0","Platform":"","Regions":[{"Name":"1","Hosts":[{"Name":"ondemand.saucelabs.com","Port":443,"Count":1,"Username":"","Password":"","VNC":"","Scheme":"https"}]}]}]}]
`

**Comment by vania-pooh** [comment]
```
[{"Name":""
```
Browser name is empty string in your config but you are passing `chrome`.

**Comment by DeChrish** [comment]
@vania-pooh yes.
I am passing chrome in the xml file, why container dont have that info?

`<qa:browsers xmlns:qa="urn:config.gridrouter.qatools.ru"> <browser name="chrome" defaultVersion="70.0"> <version number="70.0"> <region name="1"> <host name="ondemand.saucelabs.com" port="443" count="1" username="saucelabs-id" password="saucelabs-password" scheme="https" /> </region> </version> </browser> </qa:browsers>`

**Comment by vania-pooh** [comment]
@DeChrish seeing such behavior for the first time. Let me check with your file.

**Comment by DeChrish** [comment]
@vania-pooh i have recreated every steps from beginning. Still i am not able to complete the setup.

**Comment by vania-pooh** [comment]
@DeChrish username and password should be blank in `/quota` to prevent users from fetching the password. I think now the issue is in SauceLabs settings. According to `/quota` output you have:
```
<host name="ondemand.saucelabs.com" port="80" count="1" username="saucelabs-id" password="saucelabs-password" scheme="https" />
```
But port should be `443` to work with HTTPS:
```
<host name="ondemand.saucelabs.com" port="443" count="1" username="saucelabs-id" password="saucelabs-password" scheme="https" />
```
Not sure if it works but port 80 should have `scheme = http`.

**Comment by DeChrish** [comment]
@vania-pooh ah http thing. it is working; 

Selenoid-ui can be used to see the queue /  traffic?

**Comment by vania-pooh** [comment]
@DeChrish Selenoid UI shows only Selenoid sessions. You can visualize Ggr events by sending them to e.g. ElasticSearch and then creating charts. See: http://github.com/aerokube/elk-config

**Comment by DeChrish** [comment]
@vania-pooh is it compatible with MAC OS?

**Comment by vania-pooh** [comment]
@DeChrish yes, definiteny.

**Comment by DeChrish** [comment]
@vania-pooh thanks for the support.
