### ISSUE TITLE
Linking GGR on a different host to an appium server issue

### ISSUE THREAD

**Issue by jsa34** [aerokube/ggr#274]
Hello,

I have set up an appium server on a different host to where the GGR host sits.

When I added the appium host details to the .xml file and start GGR, docker logs for GGR-UI are saying: 
2019/03/13 10:14:02 [STATUS] [Failed to fetch status: Get http://appium.host.ip:4723/status: dial tcp appium.host.ip:4723: connect: connection refused]

http://appium.host.ip:4723/status does indeed return nothing, but http://appium.host.ip:4723/wd/hub/status does return the api data.

I can't find much documentation on how to register appium host with GGR host (especially if they are on different hosts).

Any help would be much appreciated.

**Comment by vania-pooh** [comment]
@jsa34 not possible to install Appium behind GgrUI (only behind Ggr) as Appium does not have `/status` API which is present in Selenoid.

**Comment by jsa34** [comment]
how do I only connect this to GGR and not to GGR-UI, as I have it defined in my .xml and GGR is picking this up, and GGR-UI is in turn picking up GGRs statuses.
Do I need to set up a separate GGR instance for the appium host?

**Comment by vania-pooh** [comment]
@jsa34 an interesting question. I think we could suppress failed `/status` requests in Ggr UI log.

**Comment by jsa34** [comment]
I will close this as the original issue has been answered.

Thank you once again for your swift support!
