### ISSUE TITLE
Stopping quota tests on demand

### ISSUE THREAD

**Issue by topproto** [aerokube/ggr#280]
Hi Vania, I have been trying to work out if the GGR is able to stop its quota tests on demand.

If I have several quota files for multiple users and a higher priority set of tests were to be required, I want to be able to tell the GGR to stop the tests for the given quota. whilst giving a new quota file to the GGR to reload.

In my mind this would have the GGR talk to the Selenoid nodes to stop the executing containers.

Is this something that exists in the GGR itself?

**Comment by vania-pooh** [comment]
@topproto Ggr is just a smart proxy. It does what you are requesting with your tests code. You should implement such logic on your tests side.

**Comment by topproto** [comment]
Thanks. 

Closing.
