### ISSUE TITLE
ggr is not redirecting to the correct version 

### ISSUE THREAD

**Issue by sharathkonda** [aerokube/ggr#283]
I am using chrome browser with two different versions ( 75.0 and 67.0 while the default version is 75.0).
1. When I set my capability to use version 67.0, it is always using the default version 75.0.
2. I noticed that ggr is only using first set of version namespace for the browser.

Here is the sample quota file (removed open bracket)
browser name="chrome" defaultVersion="75.0">
        version number="75.0">
            region name="1">
                host name="cap2-zone4" port="80" count="5"/>
                host name="cap1-zone1" port="80" count="5"/>
            region>
        version>
        version number="67.0">
            region name="1">
                host name="skxtst00039011f" port="4444" count="5"/>
            region>
        version>
    browser>

**Comment by vania-pooh** [comment]
@sharathkonda could you show your capabilities?

**Comment by sharathkonda** [comment]
@vania-pooh I noticed the browser options, for ex: chrome options, there is no mention of version and hence couldn't redirect to the relevant one.
When I configured with Firefox and added the version in the capability, it worked fine. Somewhere in my automation script, this version assignment didn't go to the grid router.
Closing the ticket with the user error.
