### ISSUE TITLE
No possibility to run android chrome tests if there is chrome browser for web in quota.xml also

### ISSUE THREAD

**Issue by vladbeza** [aerokube/ggr#285]
ggr version: aerokube/ggr:latest-release

Hi, guys. I have encountered issue (or it is just my misunderstanding) when selenoid and appium are connected to ggr 

My test.xml in quota looks like:
```
<qa:browsers xmlns:qa="urn:config.gridrouter.qatools.ru">
    <browser name="chrome" defaultVersion="76.0">
        <version number="76.0">
        <region name="1">
            <host name="selenoid" port="4444" count="1"/>
        </region>
    </version>
    </browser>
    <browser name="Nexus 5" defaultVersion="7.1.1" platformName="Android">
        <version number="7.1.1">
        <region name="1">
            <host name="appium-android" port="4723" count="1"/>
        </region>
    </version>
    </browser>
</qa:browsers>
```

In case if I run my tests agains web chrome via selenoid everything is ok 

Bu when I try to run android tests for ChromeMobile via my appium server with next capabilities:
```
capabilities = {'platformName': 'Android',
                        'platformVersion': '7.1.1',
                        'deviceName': 'Nexus 5',
                        'browserName': 'chrome',
                        'enableVNC': is_vnc_used
                        }
```
my test launches against selenoid and chrome 76.0 node.

In case if I avoid 'browserName' capability appium fairly says: The desired capabilities must include either an app, appPackage or browserName.

What should I do to run android with chrome browser agains my appium server?

Thank you in andvance,
Vlad.

**Comment by vania-pooh** [comment]
@vladbeza you can distinguish them by platform. https://aerokube.com/ggr/latest/#_creating_quota_files There is an example with platforms here. Another option - distinguish by version, e.g. by using "mobile-76.0" as version.

**Comment by vladbeza** [comment]
@vania-pooh Seems like this workaround resolved my problem. Thank you! Closing issue
