### ISSUE TITLE
Capability to explicitly select region from quota

### ISSUE THREAD

**Issue by vdelendik** [aerokube/ggr#288]
We have internal and external hubs which can handle the same browsers/devices in different regions (ff: 45, regions: us and europe).
It would be great to have possibility to handle requests via single quota for multi regions using extra custom capabilities like "region".
For now we have to organize it using several quota files and decide on the pipeline level which quota to use (us or eu).

Attached quota seems rather stable but we can't request exact region

[quota.txt](https://github.com/aerokube/ggr/files/3617199/quota.txt)

**Comment by sagarwadhwa1** [comment]
This sounds like a good to have feature, since we already have regions defined in config files.
