### ISSUE TITLE
moon behind ggr

### ISSUE THREAD

**Issue by benzman81** [aerokube/ggr#289]
Hi,

we try to setup moon behind our ggr instance that is using some IE instances but without success. You stated here https://github.com/aerokube/moon/issues/117#issuecomment-454457805 that this sholud work.
For testing purpose I set up a moon instance in a kubernetes. This is reachable under http://mykubernetesnode:30774/wd/hub. My sample test is working against it, so moon on itself works. 
Now I put a ggr docker instance on my local machine in front of it adding this config:
```
  our IE config
  ...
  <browser name="firefox" defaultVersion="64.0">
    <version number="64.0">
      <region name="selenoid-on-moon-kubernetes">
        <host name="mykubernetesnode" port="30774" count="4" scheme="http"/>
      </region>
    </version>
  </browser>
```

Now if I run my test against GGR using IE, then it works. So GGR by itself is also working. Now, when using firefox I assumme it should connect to moon. But no session will be created. Only three lines of log displayed in ggr:
```
2019/10/08 08:28:53 [7] [0.00s] [SESSION_ATTEMPTED] [test] [10.0.2.2] [firefox-64.0] [mykubernetesnode:30774] [-] [1] [-]
2019/10/08 08:28:53 [7] [0.12s] [SESSION_FAILED] [test] [10.0.2.2] [firefox-64.0] [mykubernetesnode:30774] [-] [1] []
2019/10/08 08:28:53 [7] [0.12s] [SESSION_NOT_CREATED] [test] [10.0.2.2] [firefox-64.0] [-] [-] [-] [-]
```
No log entry appeared in moon.

What am I doing wrong?

**Comment by vania-pooh** [comment]
@benzman81 is your Ggr running in Docker container? Is it aware of `mykubernetesnode` host name?

**Comment by benzman81** [comment]
@vania-pooh yes, it is running in a docker container. I just did an exec into the ggr container and executed `ping mykubernetesnode` . No problem to ping it. I also did a `wget http://mykubernetesnode:30774/wd/hub/status` and it downloaded the moon status page, so this works, too.

**Comment by vania-pooh** [comment]
@benzman81 if that's possible could you dump the traffic between ggr and moon with `tcpdump` and check whether any HTTP requests are being sent to Moon?

**Comment by benzman81** [comment]
Yes it is ;-)

I get this:

```
Host: mykubernetesnode:30774
User-Agent: selenium/3.141.59 (java windows)
Content-Length: 195
Accept-Encoding: gzip
Authorization: Basic dGVzdDp0ZXN0LXBhc3N3b3Jk
Connection: Keep-Alive
Content-Type: application/json

{"capabilities":{"firstMatch":[{"acceptInsecureCerts":true,"browserName":"firefox"}]},"desiredCapabilities":{"acceptInsecureCerts":true,"browserName":"firefox","platform":"ANY","version":"64.0"}}

Content-Type: text/plain
Www-Authenticate: Basic realm="Moon"
Date: Wed, 09 Oct 2019 07:55:18 GMT
Content-Length: 17

401 Unauthorized
```

Since using moon directly without ggr is working without "user@password" I assume that I actually dont need a this in ggr, too.

I used your helm chart as moon installation without adding/changing any user/password. I also tried `<host name="mykubernetesnode" port="30774" count="4" scheme="http" username="test" password="test-password"/>` as this is always in your examples, but didnt work.

So any idea why I get a 401 using ggr although using moon directly doesnt? Might there be a different issue?

**Comment by vania-pooh** [comment]
@benzman81 in your example request you are sending `test:test-password` as credentials. You have:
```
Authorization: Basic dGVzdDp0ZXN0LXBhc3N3b3Jk
```
... that is to say ...
```
$ echo 'dGVzdDp0ZXN0LXBhc3N3b3Jk' | base64 -D
test:test-password
```

Do you have such credentials in Moon?

**Comment by benzman81** [comment]
Ah, so the user and pw from the call to ggr will also be used for moon? I thought the <host username... password...> is the one responsible for it. I didnt set this so I assumed that no user/pw will be sent to moon and since moon is working without user/pw right now I expected it to work.

Will try to add user and pw to moon.

**Comment by vania-pooh** [comment]
@benzman81 Ggr does not explicitly remove `Authorization` header and this works like a charm with Selenoid just because it does not have any authentication. Using Moon behind Ggr is a rare case.

**Comment by benzman81** [comment]
@vania-pooh ok, that was the issue. So ggr does not use guest quota if itselft requires a login.

**Comment by vania-pooh** [comment]
@benzman81 correct.
