### ISSUE TITLE
How to register selenoid hub on Windows OS with ggr container on mac?

### ISSUE THREAD

**Issue by Grosha** [aerokube/ggr#293]
1. I ran on mac container with **ggr**. In the file test.xml, I write host port 4445, but he started listening to 4444. It confuses me.
2. I ran in mac `selenium-server-standalone -port 4445`
3. In the VM with Windows I ran selenoid as
`C:\selenoid.exe -conf C:\browsers.json -disable-docker -limit 4 > C:\selenoid.log 2>&1`

Question:
How to register selenoid hub on Windows machine with ggr container in mac? For example, if run 
`selenium-server-standalone` as hub I register nodes from VM via request `http://ip:4444/grid/register`.

**Comment by vania-pooh** [comment]
@Grosha 
1) Ggr has no registration thus you don't need to register.
2) Ggr listen port is specified with `-listen :4445` flag.
3) What's the purpose of running Selenium server on Mac?

**Comment by Grosha** [comment]
Understood, hot to set up.
