### ISSUE TITLE
Error with creating webdriver instance while using GGR with external selenium service

### ISSUE THREAD

**Issue by harshagv** [aerokube/ggr#296]
Trying a use case to run this GGR in a RHEL box with instructions mentioned in Dockerfile.

Do I really need to install GO lang as a prerequisite to run the command:

`["/usr/bin/ggr", "-listen", ":4444", "-users", "/etc/grid-router/users.htpasswd", "-quotaDir", "/etc/grid-router/quota"]`

**Comment by vania-pooh** [comment]
@harshagv no you don't need to install Golang as Ggr is a self-contained binary with no external dependencies. You only need Golang if you wish to compile Ggr from source code.

**Comment by harshagv** [comment]
@vania-pooh could you share the GGR and GGR-UI binary?

**Comment by vania-pooh** [comment]
@harshagv they are attached to every release on [releases](https://github.com/aerokube/ggr/releases) page.

**Comment by harshagv** [comment]
@vania-pooh got it, thank you

**Comment by harshagv** [comment]
@vania-pooh got it, thank you

Quick question: Can GGR redirect the driver execution request to Selenium/Selenoid Hub running with HTTPS scheme?

e.g. **_https_**://test:test-password@localhost:4444/wd/hub

**Comment by vania-pooh** [comment]
@harshagv yes, just use `scheme="https"` in XML file. If you need to proxy to external Selenium service - it is described in docs: https://aerokube.com/ggr/latest/#_working_with_external_selenium_services

**Comment by harshagv** [comment]
@vania-pooh, you mean something like below in quota/browser.xml and quota/user.xml?
'<host name="localhost" **_scheme="https"_** port="5555" count="1"/>'

Does it require rebuild the source right?
I am not familiar with GO lang, could you please share the command to rebuild the project?

**Comment by vania-pooh** [comment]
@harshagv Correct and as I said in my first comment - no need to rebuild from source. Just use compiled binaries.

**Comment by harshagv** [comment]
Ok, you are super helpful. 
Thank you

**Comment by vania-pooh** [comment]
@harshagv your external service does not have browser name and version you are requesting in Ggr quota file. This error...
```
Error forwarding the new session cannot find ...
```
... is the response from your external service.

Btw, so far as you are using external Selenium service - take a look at our online platform: https://browsers.aerokube.com/

**Comment by harshagv** [comment]
Quick question: 
To see Grid Router UI status using <scheme>://<host:8888>/status, 
Do we really need to have  external service Hubs to have installed with Selenoid and Selenoid UI or regular selenium works?

**Comment by vania-pooh** [comment]
@harshagv Selenoid, Selenoid UI and other tools don't require regular Selenium Java components to work.
