### ISSUE TITLE
Support for proxying session video with custom name

### ISSUE THREAD

**Issue by PapoyEdits** [aerokube/ggr#300]
In the Selenoid docs it is described that you can change the name of the saved video from the session-id to something of your choosing. And then you can retrieve that specific video by using the /video/<video_name>.mp4

However, if you change the name, is there currently any support in GGR to retrieve that video? The docs only mention using the session-id, so I'm assuming there is not, but wanted to double-check to be sure. 

Either way, it's a feature that would be nice to have.

**Comment by vania-pooh** [comment]
@PapoyEdits this is technically impossible. Ggr is using first 32 symbols of session ID to determine the host where video file is actually being stored and proxies there.

**Comment by PapoyEdits** [comment]
Alright, I figured that was the case but thanks for the confirmation. We'll handle naming ourselves when saving the video afterwards instead then.
