### ISSUE TITLE
Getting a 401 Unauthorized error message, when attempting to connect to ggr with webdriver.io

### ISSUE THREAD

**Issue by dizhar** [aerokube/ggr#310]
I have tried: 
docker run -d --name \
    ggr -v /etc/grid-router/:/etc/grid-router:ro \
    --net host aerokube/ggr:latest-release

with: 
  hostname:'test:test-password@localhost.

I also also tried with the non authorized flags 
docker run -d --name \
    ggr -v /etc/grid-router/:/etc/grid-router:ro \
    --net host aerokube/ggr:latest-release - -guests-allowed

Nothing works, I always get the same error message 401 Unauthorized

Does webdriver.io work with ggr?

Do you have an example of how to setup ggr with webdriver.io?

**Comment by vania-pooh** [comment]
@dizhar take a look at this example project: https://github.com/aerokube/browsers-webdriverio-example/blob/master/wdio.conf.js

**Comment by dizhar** [comment]
Thanks for the quick reply.

The example above points webdriver.io to a selenoid.  Do you have an example of a webdriver.io pointing to a ggr?

**Comment by vania-pooh** [comment]
@dizhar there is no difference, just change host name in URL.

**Comment by dizhar** [comment]
I figured it out.  

Thanks to the example your provided. 

Instead of
  capabilities: [ 
          hostname:'test:test-password@localhos
}

the answer is:
  capabilities: [ 
             user: 'test', // Username
             key: 'test-password', // Password
             hostname:'localhost',
}

Thanks for the example.

**Comment by vania-pooh** [comment]
@dizhar ok, so closing then?

**Comment by dizhar** [comment]
Yes, you can close it. 

Thanks for the help.
