### ISSUE TITLE
Unable to include platform capabilities into Ggr

### ISSUE THREAD

**Issue by timothyjmtan** [aerokube/ggr#313]
**Issue**
I have difficulties triggering tests when I include platform capabilities into ggr quota file.

Without adding in `platform` capabilities, the routing works and I am successfully able to trigger my 
tests. 

**Information**
I am connecting Ggr to 2 different selenoid platforms: linux (w docker) and windows (w/o docker). I am trying to add in platform information so that Ggr knows which platform to route to.

Ggr is hosted on Openshift.

To add in platform information, I did the following:
- modified guest.xml to below snippet
- modified web driver code to include platform capabilities:
`options.setCapability(CapabilityType.PLATFORM_NAME, "WINDOWS"));`

However when I trigger the test, I got the following logs from Ggr:
`[UNSUPPORTED_BROWSER] [guest] [xx.xx.xx.xx] [chrome-79.0] [<node_ip>:4444] [-] [1] [-]`

From the Windows selenoid node:
Nothing - the request doesn't reach the node.

From the test executor logs:
`WebDriverException: Unsupported browser: chrome-79.0`

So it seems like the issue is in the guest.xml, but I have double checked my work and can't find any issues. Appreciate if someone could give extra eyeballs on this. Thank you!

**guest.xml:**
```
<qa:browsers xmlns:qa="urn:config.gridrouter.qatools.ru">
<browser name="chrome" defaultVersion="71.0" defaultPlatform="LINUX">
    <version number="71.0" platform="LINUX">
        ...
    </version>
    <version number="79.0" platform="WINDOWS">
        ...
    </version>
</browser>
```

**Comment by timothyjmtan** [comment]
Update for this: I changed the following:

`<version number="79.0" platform="WINDOWS">`
to:
`<version number="79.0" platform="LINUX">`

and the test executed successfully (on windows).

So I think what is going on here is that I am not passing in the platform capabilities properly from my code. Instead of passing in WINDOWS it is not passing in anything which triggers the default platform of 'LINUX'. And this doesn't match the quota file. 

I'll investigate more and see how to fix this from code.

**Comment by timothyjmtan** [comment]
I've been trying to do it like this:
`options.setCapability(CapabilityType.PLATFORM_NAME, Platform.fromString("WINDOWS")));`

Also tried with value `WIN10` on both code and `guest.xml` file but no luck. Any help would be appreciated.

**Comment by timothyjmtan** [comment]
@vania-pooh , @aandryashin , any ideas? I can't seem to find any updated documentation online on how to specify capabilities from the code. The articles are all referencing DesiredCapabilities, which is already deprecated. 

When I removed the `defaultPlatform` in `guest.xml`, the routing works but that seems to also cause `platform` info to be ignored.

**Comment by vania-pooh** [comment]
@timothyjmtan let us check.

**Comment by vania-pooh** [comment]
@timothyjmtan 

1) Did first test:
```
<qa:browsers xmlns:qa="urn:config.gridrouter.qatools.ru">
    <browser name="firefox" defaultVersion="72.0" defaultPlatform="LINUX">
        <version number="72.0" platform="LINUX">
            <region name="1">
                <host name="host-1.example.com" port="4444" count="1"/>
            </region>
        </version>
        <version number="72.0" platform="WINDOWS">
            <region name="1">
                <host name="host-2.example.com" port="4444" count="1"/>
            </region>
        </version>
    </browser>
</qa:browsers>
```
Tested that with the following capabilities `final DesiredCapabilities browser = new DesiredCapabilities("firefox", "72.0", Platform.LINUX);` we are going to `host-1.example.com`, whereas when changing to `final DesiredCapabilities browser = new DesiredCapabilities("firefox", "72.0", Platform.WINDOWS);` we are going to `host-2.example.com`.

2) Did the same test with `FirefoxOptions`. The following capabilities are successfully proxied to `host-1.example.com`:
```
FirefoxOptions browser = new FirefoxOptions();
browser.setCapability("browserVersion", "72.0");
browser.setCapability("platformName", Platform.LINUX);
```
Whereas changing platform name to `WINDOWS` does not work - we are still going to `host-1.example.com`. This will be fixed.

3) Also noticed in Chromedriver release notes for versions 77.0, 78.0 and 79.0 that there were some fixes for `platform` and `platformName` capability handling. I would check with newer browser versions.

**Comment by vania-pooh** [comment]
@timothyjmtan could you please try whether it works with `aerokube/ggr:latest` image?

**Comment by timothyjmtan** [comment]
Thanks @vania-pooh ! Will check and let you know.

**Comment by timothyjmtan** [comment]
@vania-pooh It works, thank you for the quick fix!

**Comment by vania-pooh** [comment]
@timothyjmtan ok, this should be released soon.
