### ISSUE TITLE
Unable to execute parallel test suites on multiple windows VMs using selenoid-without-docker 

### ISSUE THREAD

**Issue by timothyjmtan** [aerokube/ggr#325]
Hello,

I have setup 2 windows VMs to run selenoid-without-docker. Both have been connected successfully to a ggr router, and I am able to execute a test-suite on each node individually. 

However I am running into an issue when I try to run 2 test-suites at the same time.

**Expectation**
Since there are 2 selenoid nodes available, the ggr should route 1 test-suite to be executed by each machine without issue.

**Issue**
Whenever we run 2 test-suites in parallel, very often on one machine, after a short period of time, one of the test-suites will throw a `unable to instantiate webdriver` issue. This only happens to 1 of the VM. The other VM encounters no such issue, and test-suite is executed successfully. 

Logs from GGR:
First there will be a `[SESSION_ATTEMPTED]` followed by a `[CLIENT_DISCONNECTED]`

Once this machine is 'down', it remains down and no tests can be executed successfully to this machine. We will have to close and re-run the selenoid binary file to reboot the node before it can serve tests requests again.

I have tried to find workarounds by amending the quota guest.xml file to put these machines in different regions using `<region name=1>` but the issue still occurs.

**UPDATE**
I have also tried to run 1 test-case that will spawn 2 chrome browsers during the test execution. I am running into the same error. 

I also tried a `taskkill /f /IM chromedriver.exe` with the suspicion that maybe selenoid isn't closing the chromedrivers properly. But there was no existing process when that command was executed.

From the windows machine, here are the GGR logs that was shown. I only included the text in brackets. Let me know if you need anything else to reproduce or troubleshoot this issue:

```
[NEW_REQUEST]
[NEW_REQUEST_ACCEPTED]
[LOCATING_SERVICE]
[USING_DRIVER]
[ALLOCATING_PORT]
[ALLOCATED_PORT]
[STARTING_PROCESS]
[PROCESS_STARTED]
[PROXY_TO]
[SESSION_ATTEMPTED] [http://127.0.0.1:57694] [1]
[CLIENT_DISCONNECTED] [unknown] [10.92.xx.xx] [0.72s]
[TERMINATING_PROCESS]
[PROCESS_TERMINATED]
```

**Comment by vania-pooh** [comment]
@timothyjmtan try to place hosts in separate regions in Ggr.

**Comment by timothyjmtan** [comment]
Hi @vania-pooh , I've separated these hosts as separate regions in Ggr config file, but it still exists and I can still reproduce this issue. Is there anything else I can do to help?

**Comment by vania-pooh** [comment]
@timothyjmtan is this happening always on the same host or randomly on one of hosts?

**Comment by timothyjmtan** [comment]
@vania-pooh From observations it's occurs randomly on one of the hosts.

**Comment by vania-pooh** [comment]
@timothyjmtan could be because Ggr is skipping all fully occupied Selenoid hosts except the latest one. In case of two hosts it will wait one on of them depending on the order of selection (which is random). I think the simplest solution here is just increase session wait timeout on the client side.
