### ISSUE TITLE
Is there a way to pass Selenoid or Moon options?

### ISSUE THREAD

**Issue by SlytherinCz** [aerokube/ggr#333]
I'm currently trying to place Ggr in front of Moon and some physical devices.

When I finally got the whole constellation working, I realised I didn't see any way to pass the aforementioned options to the backends.

Did I miss something, or is this not yet supported?

**Comment by vania-pooh** [comment]
@SlytherinCz could you please clarify which options are you talking about? Ggr proxies all capabilities to respective host.

**Comment by SlytherinCz** [comment]
@vania-pooh 
Hi, sorry, it was a misconfiguration on my part.
I was refering to, for example
```
"moon:options": {
    enableVNC: true
}
```

But indeed it does work
