### ISSUE TITLE
How to get GGR Session ID

### ISSUE THREAD

**Issue by MoSedky** [aerokube/ggr#334]
I just started using GGR with Selenoid on different Hosts. While the test case is running I need to get Session ID for GGR; I tried driver.session_ID but it's not matching with Test-session-ID. Is there a way to get it for like download Videos and Logs?

**Comment by vania-pooh** [comment]
@MoSedky simply use the value you are getting from Ggr with `/video/` and `/logs/` against Ggr host and port. Ggr session ID is 32 symbols longer that real session ID, removing first 32 symbols from Ggr session ID will get real session ID.

**Comment by MoSedky** [comment]
Thanks, @vania-pooh , you are the best!
