### ISSUE TITLE
Cannot create manual session from GGR -UI interface

### ISSUE THREAD

**Issue by pranav165** [aerokube/ggr#335]
I tried to setup the GGR/GGR-UI

From the ggr -ui when i try to create a manual session following API fails.

Request URL: http://10.186.1.235:8080/wd/hub/session
Request Method: POST
Status Code: 404 Not Found

Manuall sessions however can be created from the individual selenoid instances , but not from GGR. Is this a bug or as designed ?

**Comment by vania-pooh** [comment]
@pranav165 see http://aerokube.com/selenoid-ui/latest/#_using_with_ggr_or_moon

**Comment by vania-pooh** [comment]
@pranav165 see http://aerokube.com/selenoid-ui/latest/#_using_with_ggr_or_moon

**Comment by pranav165** [comment]
Launched the Selenoid UI
sudo docker run -d --name selenoid-ui -p 8080:8080 --link ggr-ui  aerokube/selenoid-ui:latest-release --selenoid-uri http://172.18.0.1:4445 --status-uri http://172.18.0.1:8888

After this i was able to create a session , but when i try to delete the session i get below error
Request URL: http://xyz:8080/wd/hub/session/c0c10518e19743a71148091428d0e1c8b7e7677e7eb2039b4ac0744a172d74cc
Request Method: DELETE
Status Code: 404 Not Found

I think the delete api expects the real session id

**Comment by vania-pooh** [comment]
@pranav165 remove `--selenoid-uri` completely. As clearly stated in docs you have to use `--webdriver-uri` and `--status-uri` instead of `--selenoid-uri`.

**Comment by pranav165** [comment]
Issue is resolved . Thanks
