### ISSUE TITLE
Getting Machine IP Address for running Selenoid Instances

### ISSUE THREAD

**Issue by MoSedky** [aerokube/ggr#337]
I just have a question if there's an automated way for getting IP Addresses for running selenoid Instances. Currently, I have more than 50 machines running on GGr Instance, when the scripts failed, it supposed to download logs and I have to check logs for the 50 Machines to get the one of interest. Are there any API that can be executed for getting the running Selenoid Instance and therefore saves a lot of time by calling `http://ip_selenoid_hub + "/download/" + session_id + "/" + downloaded_file`

**Comment by vania-pooh** [comment]
@MoSedky Ggr can do this for you: https://aerokube.com/ggr/latest/#_proxying_downloaded_files
