### ISSUE TITLE
GGR not printing the exact version requested for in error message

### ISSUE THREAD

**Issue by prasadasokan** [aerokube/ggr#338]
When requesting a browser that isn't supported, it prints the default version for that particular browser in the error message instead of the actual version requested. 

For example. Chrome 85 is default and the following is printed when Chrome 80 is requested. 

> java.lang.Exception: org.openqa.selenium.WebDriverException: cannot create session chrome-85.0 RunId=27026869 on any hosts after 2 attempt(s), last host error was: Requested environment is not available (WARNING: The server did not provide any stacktrace information) Command duration or timeout: 6.59 seconds

**Comment by vania-pooh** [comment]
@prasadasokan check in SESSION_ATTEMPTED message whether version is actually passed in capabilities.

**Comment by prasadasokan** [comment]
@vania-pooh We are using the exact version part of the capability. We also use custom test name. If we do not use custom test name, the GGR error prints the exact version requested in it's logs. But when used with custom test name, it is printing the default browser version.

**Comment by prasadasokan** [comment]
Apart from the custom name, we are passing the following. 

```
"browserName": "chrome",
  "browserVersion": "83.0"
```
