### ISSUE TITLE
Queue Mechanism

### ISSUE THREAD

**Issue by arunganesh-a** [aerokube/ggr#345]
When the browsers in all the nodes are occupied, will the ggr assign it to the selenoid queues?.

**Comment by vania-pooh** [comment]
@arunganesh-a Ggr itself has no queue. It will distribute sessions across Selenoid instances until they are full. Queues will be used when every Selenoid is full. That usually means that your cluster is overloaded. Otherwise sessions will be distributed in uniform manner.
