### ISSUE TITLE
vulnerability issue

### ISSUE THREAD

**Issue by kenlma** [aerokube/ggr#348]
hi team
could you update docker image to fix the vulnerabilities? thanks
![image](https://user-images.githubusercontent.com/11968455/134594516-cf1b3606-f857-48ca-b50e-0ff877dd5aa7.png)

also GGR-ui
![image](https://user-images.githubusercontent.com/11968455/134594622-93c5d628-a7a1-4513-8531-e2dcfc71cfc7.png)

**Comment by vania-pooh** [comment]
Will do.

**Comment by vania-pooh** [comment]
This should have been fixed by #369.
