### ISSUE TITLE
Unable to specify empty chrome version

### ISSUE THREAD

**Issue by talgreen1** [aerokube/ggr#354]
Hello,

I would like to always use the latest Chrome version. 
When trying to use empty values for '**defaultVersion**' and '**number**' in the **quota** file, I'm getting an error:

_SessionNotCreatedException: Could not start a new session. Response code 500. Message: cannot create session chrome on any hosts after 3 attempt(s), last host error was: invalid argument: entry 0 of 'firstMatch' is invalid
from invalid argument: cannot parse capability: browserVersion_

When trying to use "latest" for both of them:
_SessionNotCreatedException: Could not start a new session. Response code 500. Message: cannot create session chrome-latest on any hosts after 3 attempt(s), last host error was: Requested environment is not available

Is there any way to perform this?

This is my quota file: 
![image](https://user-images.githubusercontent.com/26517162/153861846-b31e7d97-794a-4687-9e87-8642b9c6fe43.png)

**Comment by thanxx** [comment]
I'm in the same boat, looking a way to avoid hardcoding browser versions

**Comment by vania-pooh** [comment]
@talgreen1 just remove `defaultVersion` field.

**Comment by talgreen1** [comment]
@vania-pooh I've tried it and I'm getting this error:
_Could not start a new session. Response code 500. Message: cannot create session chrome on any hosts after 3 attempt(s), last host error was: invalid argument: entry 0 of 'firstMatch' is invalid
from invalid argument: cannot parse capability: browserVersion
from invalid argument: cannot be empty_

**Comment by vania-pooh** [comment]
@talgreen1 could you check whether this is reproducing with previous Ggr release (1.6.9)?

**Comment by talgreen1** [comment]
@vania-pooh With release 1.6.9 - it's working fine. I've tried with empty **defaultVersion** attribute and without that attribute at all - both are working fine.

**Comment by talgreen1** [comment]
@vania-pooh I'm using Java, with selenium-java version 4.1.2
