### ISSUE TITLE
504 gateway timeout on /events

### ISSUE THREAD

**Issue by bellackj** [aerokube/ggr#357]
I'm running ggr with selenium on 4 containers on an EC2 instance in AWS. Getting a 504 Gateway timeout trying to access the /events path. myselenium.com and myselenium.com/status both return as expected

**Comment by vania-pooh** [comment]
@bellackj Ggr has no such API. `/events` exists only in Selenoid UI and is a using a long-lasting connection (SSE, server-sent events). So if you are running our tools behind some reverse proxy like Nginx, you may need to increase proxy timeout there.

**Comment by bellackj** [comment]
I figured out my issue. I'm running behind an ALB which had default idle timeout set to 60s. Changed to 300s and now working as expected.
