### ISSUE TITLE
INVALID_URL every run test via ggr

### ISSUE THREAD

**Issue by kuproydev** [aerokube/ggr#360]
Hi, i have followed [readme](https://github.com/aerokube/ggr/blob/master/README.md) and [ggr docs ](https://aerokube.com/ggr/latest/#_getting_started) but when running the test the results are the same as the picture below. Is there anything I missed?
<img width="674" alt="CleanShot 2022-04-11 at 16 51 46@2x" src="https://user-images.githubusercontent.com/103420211/162713587-5aa6a835-c3b1-427b-b6df-91d3860430c1.png">

**Comment by vania-pooh** [comment]
@kuproydev should be `/wd/hub/session/<id>/url` and so on/

**Comment by kuproydev** [comment]
Yeah, this doesn't work when using selenium grid. when i use selenoid it works fine.
Thank you

**Comment by kuproydev** [comment]
@vania-pooh  yes you are right, but when I use selenium grid, session is successfully forwarded, but browser is not launched. is there anything i missed?
<img width="467" alt="CleanShot 2022-04-13 at 19 40 34@2x" src="https://user-images.githubusercontent.com/103420211/163182007-85d6b710-824d-4187-bd15-d67b8e7c5b70.png">
<img width="814" alt="CleanShot 2022-04-13 at 19 35 10@2x" src="https://user-images.githubusercontent.com/103420211/163181013-8cc351da-c289-4d6a-991c-869f10411dd8.png">
this is my configurations
selenium command
```console
java -jar selenium-server-4.1.0.jar standalone --port 4445
```
ggr command
```console
 ./ggr -verbose
```
quota
```xml
<qa:browsers xmlns:qa="urn:config.gridrouter.qatools.ru">
<browser name="safari" defaultVersion="15.4">
    <version number="15.4">
        <region name="1">
            <host name="localhost" port="4445" count="1"/>
        </region>
    </version>
</browser>
<browser name="chrome" defaultVersion="100.0">
    <version number="100.0">
        <region name="1">
            <host name="localhost" port="4445" count="1"/>
        </region>
    </version>
</browser>
</qa:browsers>
```
curl
```console
curl -H "Content-Type:application/json;charset=utf-8" --data '{"capabilities": {"alwaysMatch": {"browserName": "chrome"}}}' http://admin:admin@localhost:4444/wd/hub/session
```

**Comment by vania-pooh** [comment]
@kuproydev they could have changed base URL to just `/`, so instead of `http://some-host.example.com:4444/wd/hub` in Selenium Grid 4 base URL could be `http://some-host.example.com:4444/`.

**Comment by kuproydev** [comment]
@vania-pooh 
Is it like this? they return 404
<img width="982" alt="CleanShot 2022-04-13 at 22 21 25@2x" src="https://user-images.githubusercontent.com/103420211/163214613-ae9ece1d-9ef2-4b28-ab66-deedf4fa946d.png">

**Comment by vania-pooh** [comment]
@kuproydev yes, request is correct. In that case have no idea about the reason.
