### ISSUE TITLE
ggr starting two nodes instead of one and using a lot of CPU

### ISSUE THREAD

**Issue by Evolutiounx** [aerokube/ggr#361]
Hi, so my problem is, I was using one selenoid server with all working fine and then decided that I needed to scale it so I created several other servers that also have selenoid servers running.
So I've setup ggr on machine 1 and have machine 1, machine 2 and machine 3 running selenoid and selenoid-ui.
And when I start my selenium script it creates the sessions evenly across all the machines, the problem is that instead of only creating one node I think it's creating two, when I look into the selenoid panel and in the docker logs I see there that only one session was created but when I look into the docker containers running I see this:

![image](https://user-images.githubusercontent.com/37879180/163502798-554b099f-0579-4f87-bb8a-b575a7d2f8e2.png)

The one underlined in blue I think it is the node created for the session but it also created the one highlighted in red that is consuming the whole CPU and is receiving a ton of data from the container underlined in blue I believe, since the amount of data sent by blue matches the amount of data received by red, as we can see in the "NET I/O" stats, I have no idea what that is but I would want that container that is being created underlined in red to not show since instead of being able to run around 30 sessions at the same time I would only be able to start 2 with some luck because of how much CPU it is consuming.

**This is my xml config:**

```
<qa:browsers xmlns:qa="urn:config.gridrouter.qatools.ru">
<browser name="chrome" defaultVersion="100.0">
    <version number="100.0" platform="LINUX">
        <region name="1">
            <host name="[MACHINE 1 IP]" port="4444" count="1" />
            <host name="[MACHINE 2 IP]" port="4444" count="1" />
            <host name="[MACHINE 3 IP]" port="4444" count="1" />
        </region>
    </version>
</browser>
</qa:browsers>

```

**I used that commands to start selenoid:**
./cm selenoid start --args "-limit 30"

**And this one to start selenoid-ui and link the ggr-ui to it:**
docker run -d --name selenoid-ui -p 8080:8080 aerokube/selenoid-ui:latest-release --selenoid-uri http://[IP OF MACHINE 1]:8888

**Comment by vania-pooh** [comment]
@Evolutiounx GGR always send exactly 1 new session request per host. So Ggr is not the cause of this behaviour.

**Comment by Evolutiounx** [comment]
You're right, I started the script using only an individual machine with just selenoid without ggr and the same problem persisted. Then I tried to disable the video recording function and now the problem is gone, it seems it was the video recording that was uploading/downloading 100Mb of data per second and using 50% of the CPU. 
Do you by any chance have any idea on how to fix that? Video is handy for debugging, it's not the end of the world but would be nice if I would be able to have it back without the issue.

**Comment by vania-pooh** [comment]
@Evolutiounx you can try to decrease screen resolution or frame rate using Selenoid capabilities. But we recommend to record videos for failed test cases only.
