### ISSUE TITLE
selenium webdriver can't connect to devtools websocket

### ISSUE THREAD

**Issue by NathanFRuiz** [aerokube/ggr#362]
when trying get selenium library to connect to the devtools web socket i'm getting the following error when proxying through ggr, is the devtools websocket savailable out of the box or does it demand extra settings?

```
Unhandled exception. OpenQA.Selenium.WebDriverException: Unexpected error creating WebSocket DevTools session.
 ---> System.Net.WebSockets.WebSocketException (0x80004005): The server returned status code '400' when status code '101' was expected.
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at OpenQA.Selenium.DevTools.DevToolsSession.InitializeSocketConnection()
   at OpenQA.Selenium.DevTools.DevToolsSession.StartSession(Int32 requestedProtocolVersion)
   at OpenQA.Selenium.Remote.RemoteWebDriver.GetDevToolsSession(Int32 protocolVersion)
   --- End of inner exception stack trace -
```

I've tried to add the following to the quota file but had no luck

`<host name="{host_ip}" port="4444" vnc="ws://{host_ip}:4444/vnc" devtools="ws://{host_ip}:4444/devtools" count="1"/>`

**Comment by vania-pooh** [comment]
@NathanFRuiz we never said that Selenium 4 devtools is supported in Selenoid \ Ggr.

**Comment by NathanFRuiz** [comment]
Got it, I was lead to think that by this session on documentation:
![image](https://user-images.githubusercontent.com/79537306/165961775-3128e088-559f-4136-8a98-d4a66f7e5e7c.png)

But we can work around it somehow, thanks for your time.

**Comment by vania-pooh** [comment]
@NathanFRuiz yes, this feature works. But Selenium 4 also requires processing additional capabilities and this is not currently implemented in Selenoid \ Ggr.
