### ISSUE TITLE
Unable to run UI Test Case using Selenium 4 thru ggr on Selenoid and getting System.ArgumentException : elementDictionary (Parameter 'The specified dictionary does not contain an element reference')

### ISSUE THREAD

**Issue by bharatgarg211** [aerokube/ggr#363]
Hi All,

Please assist us.. we are trying to run our selenium test cases on Selenoid via ggr but getting below error 
System.ArgumentException : elementDictionary (Parameter 'The specified dictionary does not contain an element reference')

ChromeDriver Used : Latest
Chrome : latest
ggr : latest
Selenium Version :  Version of Selenium 4 i.e. 4.1.0

Also tried solution given here : https://github.com/aerokube/ggr/issues/354 but no luck by replacing default Version as below in quota file 
![image](https://user-images.githubusercontent.com/90189068/165969267-d7d86a26-cc76-4990-b0e9-ea3e9e7f88b8.png)

Test cases are running fine with Selenium 3.141

**Comment by bharatgarg211** [comment]
Can anyone please assist in resolving this issue

**Comment by vania-pooh** [comment]
@bharatgarg211 this is an issue in your code, not Ggr.

**Comment by bharatgarg211** [comment]
@vania-pooh can you please assist what can be proable reason in code

**Comment by vania-pooh** [comment]
@bharatgarg211 please show your capabilities.
