### ISSUE TITLE
Is there a way to delete all the ggr logs? 

### ISSUE THREAD

**Issue by dibyaranjan-pg** [aerokube/ggr#364]
I am keep getting below error while trying to delete all the logs in ggr
`DELETE : http://<ggr-hostname>:4444/logs`
`{
    "status": 13,
    "value": {
        "message": "invalid request URL"
    }
}`

**Comment by vania-pooh** [comment]
@dibyaranjan-pg there is no such feature because logs are stored on Selenoid side.
