### ISSUE TITLE
Is OKTA supported by GGR

### ISSUE THREAD

**Issue by Puvvada-Ananth** [aerokube/ggr#368]
Hi Team,
We are exploring GGR and wanted to know if their is any way that GGR supports OKTA.

**Comment by vania-pooh** [comment]
@Puvvada-Ananth no, Ggr only supports static credentials. But [Moon](https://aerokube.com/moon/) supports OpenID connect, i.e. will work with Okta.

**Comment by Puvvada-Ananth** [comment]
Awesome such a fast reply. thank you.
