### ISSUE TITLE
[Too Many Requests] issue

### ISSUE THREAD

**Issue by Puvvada-Ananth** [aerokube/ggr#370]
Hi Team,

Before coming to issue, My GGR node and selenoid agents are health with no issues and we are able to see that few sessions are already running and able to see them from selenoid UI

- What happens to the session if the log looks like below in GGR logs,

I got the below logs by running **docker logs -f ggr**

**2023/02/03 13:30:31 [5586229] [0.09s] [SESSION_FAILED] [xxxxxxx] [172.17.0.1] [chrome-latest] [10.229.219.111:4444] [-] [1] [Too Many Requests]**

- Is their any chance that the session will fail with attached screenshot error if i see the log like above?

![image](https://user-images.githubusercontent.com/106600556/216616701-1bc3b67e-a496-4402-8ef1-e5cb467fc712.png)

**Comment by vania-pooh** [comment]
@Puvvada-Ananth that means all browser slots on this host were already taken and Ggr selected another host. However when all hosts were tried Ggr will wait on the last one until session is created or your code disconnects. So the reason of this exception in your code is that you took all available browsers.
