### ISSUE TITLE
How can we access GGR logs form GGR UI?

### ISSUE THREAD

**Issue by Puvvada-Ananth** [aerokube/ggr#371]
Hi Team,

Do we have a way to access GGR container logs from GGR UI or Selenoid UI. We are using following commands to configure GGR and Selenoid agents 
**GGR Node configuration
----------------------------------**
docker pull aerokube/ggr:latest 
docker pull aerokube/ggr-ui:latest-release 
docker pull aerokube/selenoid-ui:latest 
docker run -d --name ggr --restart=always -p 4444:4444 -v /c/Users/sai/Desktop/ggr:/etc/grid-router  aerokube/ggr:latest 
docker run -d --name ggr-ui --restart=always -p 8888:8888 -v /c/Users/sai/Desktop/ggr:/etc/grid-router aerokube/ggr-ui:latest-release 
docker run -d --name selenoid-ui --restart=always -p 8080:8080 aerokube/selenoid-ui:latest --selenoid-uri http://10.119.112.101:8888 

**Selenoid agent configuration
----------------------------------------------**
docker pull selenoid/chrome:latest 
docker pull selenoid/video-recorder:latest-release 
docker pull aerokube/selenoid:latest 
docker run --restart=always -d --name selenoid -p 4444:4444 -v /var/run/docker.sock:/var/run/docker.sock -v /home/sai/selenoid/config:/etc/selenoid/:ro -v /home/sai/selenoid/video:/opt/selenoid/video -e OVERRIDE_VIDEO_OUTPUT_DIR=/home/sai/selenoid/video aerokube/selenoid:latest -timeout 15m -session-attempt-timeout 15m -video-output-dir /opt/selenoid/video -limit 8 -log-output-dir /opt/selenoid/logs

**Comment by vania-pooh** [comment]
@Puvvada-Ananth not possible. ggr-ui is only needed for merging `/status` API from multiple Selenoid instances.
