### ISSUE TITLE
Using W3C protocol extensions Selenoid labels are missing in log files

### ISSUE THREAD

**Issue by martingrossmann** [aerokube/ggr#384]
With Selenium 4 I have to use the W3C protocol extensions for custom capabilties like for Selenoid.

Adding labels to `selenoid:options` they aren't visible any more in GGR logs:

__Selenium 3 caps__
```
{
  "browserName": "chrome",
  "enableVNC": true,
  "enableVideo": true,
  "goog:chromeOptions": {
    "args": [
      "--no-sandbox"
    ],
    "extensions": []
  },
  "labels": {
    "foo": "bar"
  },
  "version": "114",
  "videoName": "myvideoname.mp4"
}
```
results in GGR log
`2023/09/15 14:32:36 [2731] [2.19s] [SESSION_CREATED] [test] [10.xx.xx.xx] [chrome-114 foo=bar] [192.168.xx.xx:5001] [129d5982f2c3221dd7faec52cff0e614] [1] [-]`
--> OK

__Selenium 4 caps__
```
{
  "browserName": "chrome",
  "goog:chromeOptions": {
    "args": [
      "--no-sandbox"
    ],
    "extensions": []
  },
  "selenoid:options": {
    "enableVNC": true,
    "videoName": "myvideoname.mp4",
    "enableVideo": true,
    "labels": {
      "foo": "bar"
    }
  },
  "version": "114"
}
```
results in GGR log
`2023/09/15 14:37:44 [3226] [2.01s] [SESSION_CREATED] [test] [10.xx.xx.xx] [chrome-114] [192.168.xx.xx:5002] [14bba25c7a8c47b56aeb2fb0bf1f3cae] [1] [-]`
--> Not OK. Only browser was added, but no labels

**Comment by martingrossmann** [comment]
@vania-pooh Hi, can you confirm that? Could there be a workaround?

**Comment by vania-pooh** [comment]
@martingrossmann sorry for the delay. Checked source code. Currently `selenoid:options` namespace is not supported in Ggr. Ggr is only able to get keys either from `desiredCapabilities` or from `capabilities > alwaysMatch \ firstMatch` on the top level. So it will work like this:

```
{"capabilities": {"alwaysMatch": {"labels": {...}}}}
```

But this does not correspond to W3C standard. Probably we may need to add `selenoid:options` or `ggr:options` key and support it in Ggr.

**Comment by gogro** [comment]
please do if you find the time, would be much appreciated.

**Comment by vania-pooh** [comment]
This was released in https://github.com/aerokube/ggr/releases/tag/1.7.2.
