### ISSUE TITLE
Count field in quota XML is ignored

### ISSUE THREAD

**Issue by nebehr** [aerokube/ggr#69]
It was my understanding that "count" field in the quota is used to restrict the number of browsers available to a user. However I can actually get as many browsers as there are available on the underlying selenoid node.

I have ggr with single selenoid (both latest) running on the same virtual box. Selenoid has default limit of containers (5). In my quota file (test.xml) a have set count to 1 for each browser:
```
<qa:browsers xmlns:qa="urn:config.gridrouter.qatools.ru">
<browser name="chrome" defaultVersion="58.0">
    <version number="58.0">
        <region name="1">
            <host name="127.0.0.1" port="4444" count="1"/>
        </region>
    </version>
</browser>
</qa:browsers>
```

When I run the following code I am getting all three browsers I have requested:
```
DesiredCapabilities caps = DesiredCapabilities.chrome();
WebDriver w1 = new RemoteWebDriver(url, caps);
WebDriver w2 = new RemoteWebDriver(url, caps);
WebDriver w3 = new RemoteWebDriver(url, caps);
```
ggr container logs show 3 corresponding "SESSION_CREATED" entries. 

If my assumption regarding "count" is wrong could you please provide some explanation on how otherwise to limit the number of browsers available to a specific user.

**Comment by vania-pooh** [comment]
@nebehr this field is in fact a "host weight". So having two hosts you can adjust counts e.g. to `2` and `3` and Ggr will distribute requests in the same proportion. With one host this field is meaningless and can have any value. The only way to limit total number of sessions is to adjust Selenoid limit. Selenoid contarily to Ggr (which is just a smart proxy) can place your request to its internal queue.

**Comment by nebehr** [comment]
Thanks for the explanation. Maybe it should then be renamed to "weight" to avoid confusion? Just a suggestion.

**Comment by vania-pooh** [comment]
@nebehr this name comes from original [GridRouter](http://github.com/seleniumkit/gridrouter). So for compatibility purposes I wouldn't rename the field right now.

**Comment by nebehr** [comment]
So correct me if I'm wrong, there is basically no way to manage allowed browser instances per user in a configuration similar to [this](http://aerokube.com/ggr/latest/img/multiple-ggr.png) where Selenoid instances are shared between ggr's, is that right? And therefore the only way to achieve it would be to have a dedicated Selenoid (or set of Selenoids) with appropriate limit for every user?

Btw, is there a discussion board for these tools? I am not sure if I should be asking these questions in this issue in the first place.

**Comment by vania-pooh** [comment]
@nebehr we have Telegram channel https://t.me/joinchat/AAAAAAkZ1DfzAv-eYWTlTQ and support email support@aerokube.com. To completely isolate hosts for different users in Ggr you need to create separate quota files. Otherwise this host will be shared among users. This allows to create different username-password pairs but use the same hosts to launch browsers.

**Comment by DeChrish** [comment]
> @nebehr this field is in fact a "host weight". So having two hosts you can adjust counts e.g. to `2` and `3` and Ggr will distribute requests in the same proportion. With one host this field is meaningless and can have any value. The only way to limit total number of sessions is to adjust Selenoid limit. Selenoid contarily to Ggr (which is just a smart proxy) can place your request to its internal queue.

-- @vania-pooh  are you recommending to create proxy to route the request to its internal queue? selenoid will not automatically do?
