### ISSUE TITLE
Ability to specify username and password for downstream server

### ISSUE THREAD

**Issue by vania-pooh** [aerokube/ggr#93]
In quota XML we specify username and password for host like the following:
```
<host name="downstream-host.example.com" port="5555" count="5" username="test" password="test-password"/>
```
When creating new session we override passed username and password with new ones. This gives two things:
1) Creating a hierarchy of Ggr instances
2) Ability to work with external commercial services

**Comment by vgrigoruk** [comment]
guys, you're killing zalenium :)
