### ISSUE TITLE
Get IP:port of the hub where the driver is 

### ISSUE THREAD

**Issue by MiluchOK** [aerokube/ggr#97]
It would be extremely useful if the router had an end point which I can hit with the session id and get the hub info.

**Comment by vania-pooh** [comment]
What is the use case for this feature?

**Comment by MiluchOK** [comment]
Well, for my use case, I need to know which node I am running the session on. To get the node, I need to query the hub, to query the hub I need to know which hub I am using. I haven't looked into the code much, but aren't you doing a look up on which hub the session belongs to?

**Comment by MiluchOK** [comment]
Or if you have tips on how I can do that without the endpoint, you'll save my ass big time.

**Comment by vania-pooh** [comment]
@MiluchOK session ID stores this information. Ggr automatically adds md5sum("http://example.com:4444") to every session ID. So you can calculate MD5 sum for each host once and then match first 32 symbols of session ID to host name. Take a look at more detailed explanation here: http://aerokube.com/ggr/latest/#_why_ggr_is_stateless

**Comment by MiluchOK** [comment]
Ok, thanks!

**Comment by vania-pooh** [comment]
Please try this approach and tell me whether it is suitable.

**Comment by MiluchOK** [comment]
I will, but still for the solution to be rock solid it would be nice to have an end point where I supply my session id and the response contain hub ,so my code still works if you decide to change the router implementation and count something else but MD5.

**Comment by MiluchOK** [comment]
Hope it makes any sense.

**Comment by vania-pooh** [comment]
@MiluchOK let me discuss this feature with the team. It does not contradict to architecture so it is very possible that is gets implemented.

**Comment by vania-pooh** [comment]
@MiluchOK ok, we'll implement it. How would you expect to obtain the result, i.e. should return just hostname as `text\plain` or some JSON?

**Comment by vania-pooh** [comment]
Currently my proposal is:
```
$ curl http://localhost:4444/host/<session_id>

{"host": "example.com"}
```
In command-line this can be easily parsed with such tools as `jq`.

**Comment by MiluchOK** [comment]
JSON sounds great! Let me test it out.

**Comment by MiluchOK** [comment]
Have you merged to master yet?

**Comment by vania-pooh** [comment]
Will merge tomorrow.

**Comment by MiluchOK** [comment]
Waiting! Just in case if this info is useful ,the reason why I need execution node info is because I have few zalenium grids running behind your router. Zalenium gives liveview ability and it is a neat feature to link each 'in progress' test to it's liveview window. 

Also I'll be able to get downloaded through a browser to nodes files.

**Comment by vania-pooh** [comment]
@MiluchOK you can test this feature with `aerokube/ggr:latest` like the following:
```
$ curl http://localhost:4444/host/<session_id>

{"name": "example.com", "port": 4444, count: 1}
```
Regarding Zalenium - I would recommend you to try our tool called Selenoid: https://github.com/aerokube/selenoid It also provides you the liveview ability. Further reading: https://medium.com/@aandryashin/selenium-easy-as-a-pie-df8b5876b541 Please also take a look at documentation: http://aerokube.com/selenoid/latest/
